import type { RequirementRegistry } from './schema';

const relatedFiles = [
  'src/components/UploadQuestionDialog.tsx',
  'src/app/homework/page.tsx',
  'src/app/api/recognize-questions/route.ts',
  'src/lib/ai-recognizer.ts',
  'src/app/paper-edit/page.tsx',
];
const decisionFile = 'docs/prd-workflow/decisions/question-answer-review-step.decision.md';

const pageName = '核对识别结果';
const route = '/homework → 识别作业资料 → 核对识别结果';
const moduleName = '识别作业资料';

function activateReview(anchorId: string) {
  return [
    { type: 'openDialog' as const, label: '打开识别作业资料弹窗', dialog: 'UploadQuestionDialog' },
    { type: 'setStep' as const, label: '切换到核对识别结果步骤', step: 'review' },
    { type: 'scrollTo' as const, label: '定位页面对象', anchorId },
    { type: 'highlight' as const, label: '高亮页面对象', anchorId },
  ];
}

export const questionAnswerReviewStepRegistry: RequirementRegistry = {
  registryId: 'question-answer-review-step',
  pageName,
  route,
  module: moduleName,
  description: '记录步骤 4「核对识别结果」的完整页面逻辑，覆盖匹配状态提示、题目卡片展示、题目卡片排序与删除、子题结构与编辑、答案/解析核对与关联、题型切换保护、图片模式与编辑模式切换、加入试卷等交互边界。',
  sourceDecisionFile: decisionFile,
  relatedFiles,
  requirements: [
    {
      id: 'REVIEW_STEP-001',
      title: '匹配状态提示（分步模式）',
      sourceType: 'code+decision',
      objectType: 'region',
      objectName: '匹配状态提示条',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-match-banner',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-match-banner'),
      display: {
        title: '匹配状态提示',
        description: '题目+答案模式下，右侧面板顶部显示匹配状态提示条。存在待匹配题目时：「识别结果：共 X 道题目，已匹配答案 Y 题，待匹配答案 N 题（待匹配答案的题目，可在左侧框选答案/解析手动关联题目）」。全部匹配后：「全部题目已匹配答案和解析，可将题目加入试卷了~」。提示条始终完整展示，不可收起或展开。',
        fields: ['父题数量', '已匹配答案数量', '待匹配答案数量'],
        states: ['存在待匹配题目', '全部匹配'],
      },
      operation: {
        title: '查看匹配进度',
        description: '提示条不可点击、不可收起、不可展开。存在待匹配题目时，用户可通过左侧框选答案/解析手动关联。',
        permission: '无额外权限限制',
        dataFlow: '匹配统计根据已识别的题目、答案和解析数据计算。',
        exceptions: '没有识别结果时不展示。',
      },
      acceptance: [
        '存在待匹配题目时，提示条正确显示识别结果统计',
        '待匹配数量正确',
        '全部题目均已匹配答案/解析时，提示条显示「全部题目已匹配答案和解析，可将题目加入试卷了~」',
      ],
      source: { decisionFile, decisionObject: '答案匹配状态与统计', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-002',
      title: '题目卡片展示（仅识别题目模式）',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.21',
      objectType: 'region',
      objectName: '题目卡片（仅识别题目模式）',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-question-card-single',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-question-card-single'),
      display: {
        title: '仅识别题目模式下的题目卡片',
        description: '仅识别题目模式下，右侧按题号展示每道题目。题号顺序以左侧资料页为准；补识别新增题按题号插入已有题目之间；重识别同题号题干时原位置覆盖。每张卡片含题号、题型、题目内容和图片预览，不展示答案/解析区域。【6.21】系统识别为填空题时，首次呈现自动使用该题编辑模式，如果用户手动切回图片模式，题型后显示提示「图片模式下暂不支持【填空题】，可切换至编辑模式处理」。【6.21】系统识别为断句题时，题型兜底显示为问答题，并在题型后显示提示「系统暂不支持【断句题】，建议用问答题题型替代」。',
        fields: ['题号', '题型', '题目内容', '图片预览', '【6.21】填空题图片模式提示', '【6.21】断句题兜底提示'],
        states: [
          '图片模式：显示截图',
          '编辑模式：显示识别文字',
          '新增题：按题号插入',
          '重识别题：原位置覆盖',
          '【6.21】填空题首次呈现：单题自动使用编辑模式',
          '【6.21】断句题：题型显示为问答题并展示断句题不支持提示',
        ],
      },
      operation: {
        title: '核对与编辑',
        description: '1、可切换图片模式查看截图或编辑模式修改文字。\n2、两种模式下均可修改题型。\n3、点击左侧题号框可定位到右侧对应题目，点击右侧题号可定位到左侧对应资料位置。\n4、编辑模式下可修改题目内容。\n5、可使用裁剪功能截取题目图片。\n6、可为复合题添加子题。\n7、补识别新增题：左侧框选漏掉题干后点击开始识别，新题卡按题号插入。\n8、重识别已有题：重新框选完整题干后点击开始识别，原题卡覆盖更新。\n【6.21】对已识别选框调整后点击「更新识别结果」，右侧采用覆盖当前对应题卡的方式处理，不按新增题卡处理。',
        permission: '无额外权限限制',
        dataFlow: '题目数据来源于 AI 识别结果。新增题按题号插入，重识别同题号覆盖原题卡。用户编辑后更新本地状态，加入试卷时传递给下游。',
        exceptions: '识别失败时停留在框选阶段。',
      },
      acceptance: [
        '题目卡片正确展示',
        '右侧题号顺序应以左侧资料页题号顺序为准',
        '点击左侧题号框时右侧自动定位到对应题目',
        '单击右侧题号时左侧自动定位到对应资料位置',
        '图片/编辑模式可切换',
        '题型和内容可编辑',
        '裁剪功能可用',
        '第4步补识别新增题后应按题号插入列表',
        '第4步重识别重复题后应原位置覆盖',
        '【6.21】调整已识别选框后更新识别结果，应覆盖当前对应题卡而不是新增题卡',
        '【6.21】填空题首次呈现自动使用单题编辑模式，手动切回图片模式时展示填空题图片模式不支持提示',
        '【6.21】断句题兜底显示为问答题，并展示断句题不支持提示',
      ],
      source: { decisionFile, decisionObject: '仅识别题目模式展示 / 6.21 需求评审异常场景', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-003',
      title: '题目卡片展示（识别题目和答案模式）',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.21',
      objectType: 'region',
      objectName: '题目卡片（识别题目和答案模式）',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-question-card-stepwise',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-question-card-stepwise'),
      display: {
        title: '题目+答案模式下的题目卡片',
        description: '题目+答案模式下，右侧按题号展示每道题目。题号顺序以左侧资料页为准。每张卡片含题号、题型、题目内容、答案区域和解析区域。匹配状态用四种标签区分：「答案解析已匹配」「未匹配到答案」「未匹配到解析」「未匹配到答案和解析」。填空题按空位展示答案，解答题按子题结构展示子题答案和解析。补识别新增题按题号插入，重识别同题号题干时原位置覆盖。【6.21】系统识别为填空题时，首次呈现自动使用该题编辑模式，如果用户手动切回图片模式，题型后显示提示「图片模式下暂不支持【填空题】，可切换至编辑模式处理」。【6.21】系统识别为断句题时，题型兜底显示为问答题，并在题型后显示提示「系统暂不支持【断句题】，建议用问答题题型替代」。',
        fields: ['题号', '题型', '题目内容', '答案', '解析', '匹配状态标签', '子题答案/解析', '【6.21】填空题图片模式提示', '【6.21】断句题兜底提示'],
        states: [
          '答案和解析均匹配：显示「答案解析已匹配」',
          '未匹配到答案：显示「未匹配到答案」',
          '未匹配到解析：显示「未匹配到解析」',
          '未匹配到答案和解析：显示「未匹配到答案和解析」',
          '四种标签样式有区分',
          '图片模式：显示截图',
          '编辑模式：显示识别文字',
          '新增题：按题号插入',
          '重识别题：原位置覆盖',
          '【6.21】填空题首次呈现：单题自动使用编辑模式',
          '【6.21】断句题：题型显示为问答题并展示断句题不支持提示',
        ],
      },
      operation: {
        title: '核对与编辑',
        description: '1、可切换图片模式查看截图或编辑模式修改文字。\n2、两种模式下均可修改题型、编辑答案和解析。\n3、点击左侧题号框可定位到右侧对应题目，点击右侧题号可定位到左侧对应资料位置。\n4、编辑模式下可修改题目内容。\n5、可使用裁剪功能截取题目图片。\n6、可为复合题添加子题。\n7、未匹配答案时，可通过再次框选并点击开始识别更新结果；也可点击【答案】【解析】后的关联图标进入关联态，跨文件模式下自动定位到答案文件位置，无法定位到具体位置则定位到答案文件开始位置。\n8、补识别新增题：左侧框选漏掉题干后点击开始识别，新题卡按题号插入。\n9、重识别已有题：重新框选完整题干后点击开始识别，原题卡覆盖更新。\n【6.21】对已识别选框调整后点击「更新识别结果」，右侧采用覆盖当前对应题卡的方式处理，不按新增题卡处理。',
        permission: '无额外权限限制',
        dataFlow: '题目数据来源于 AI 识别和答案匹配结果。新增题按题号插入，重识别同题号覆盖原题卡。用户编辑后更新本地状态，加入试卷时传递给下游。',
        exceptions: '识别失败时停留在框选阶段。',
      },
      acceptance: [
        '题目卡片含答案和解析区域',
        '右侧题号顺序应以左侧资料页题号顺序为准',
        '四种答案/解析匹配状态标签正确显示且样式有区分',
        '点击左侧题号框时右侧自动定位到对应题目',
        '单击右侧题号时左侧自动定位到对应资料位置',
        '未匹配答案时可通过再次框选并开始识别更新结果',
        '答案/解析关联图标可引导用户定位答案文件并进入关联状态',
        '填空题按空位显示答案',
        '解答题显示子题结构',
        '图片/编辑模式可切换',
        '第4步补识别新增题后应按题号插入列表',
        '第4步重识别重复题后应原位置覆盖',
        '【6.21】调整已识别选框后更新识别结果，应覆盖当前对应题卡而不是新增题卡',
        '【6.21】填空题首次呈现自动使用单题编辑模式，手动切回图片模式时展示填空题图片模式不支持提示',
        '【6.21】断句题兜底显示为问答题，并展示断句题不支持提示',
      ],
      source: { decisionFile, decisionObject: '题目+答案模式展示 / 6.21 需求评审异常场景', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-004',
      title: '子题结构与编辑',
      sourceType: 'code+decision',
      objectType: 'region',
      objectName: '子题结构区域',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-subquestion',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-subquestion'),
      display: {
        title: '子题结构',
        description: '复合题型（解答题、完形填空、阅读理解等）支持子题结构。识别时系统自动拆分大题的子题，右侧展示时已添加好子题，每个子题含序号（①②③...）、自动匹配的题型、答案和解析区域。父题无需显示子题匹配进度标签。乐课网资源库中无子题的大题不显示【+子题】按钮。',
        fields: ['子题序号', '子题题型', '子题答案', '子题解析', '+子题按钮', '删除子题按钮'],
        states: [
          '资源库无子题的大题：不显示【+子题】',
          '新增子题：空子题',
          '无法拆分答案/解析：父题区显示「答案解析待人工拆分」',
          '已手动拆分：隐藏「答案解析待人工拆分」标签',
          '删除子题确认弹窗',
        ],
      },
      operation: {
        title: '子题编辑',
        description: '1、题干子题标记≥2时系统自动生成子题结构。\n2、子题题型根据题干要求自动匹配，不固定继承父题。\n3、子题题型可选项根据菁优网的题型显示。\n4、答案/解析按子题标记自动拆分；无法拆分时保留在父题区并显示「答案解析待人工拆分」，手动拆分后标签隐藏。\n5、资源库无子题的大题不显示【+子题】。\n6、点击「+子题」新增空子题。\n7、删除有内容的子题时弹窗确认：「该子题已有答案/解析，删除后内容将一并移除，是否继续？」',
        permission: '无额外权限限制',
        dataFlow: '子题数据作为题目数据的一部分，加入试卷时保留完整子题结构。',
        exceptions: '题干少于2个子题标记时不自动生成子题结构。',
      },
      acceptance: [
        '子题自动拆分正确',
        '子题题型自动匹配',
        '无法拆分时显示「答案解析待人工拆分」标签',
        '手动拆分答案与解析后隐藏「答案解析待人工拆分」标签',
        '资源库无子题的大题不显示【+子题】按钮',
        '新增子题为空',
        '删除有内容的子题弹窗确认',
        '加入试卷保留子题结构',
      ],
      source: { decisionFile, decisionObject: '子题结构与编辑', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-005',
      title: '答案关联icon',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.21',
      objectType: 'button',
      objectName: '答案/解析关联图标',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-answer-link-icon',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-answer-link-icon'),
      display: {
        title: '答案关联icon',
        description: '每道题的「答案」「解析」标题后方显示轻量关联图标。跨文件模式下点击后左侧资料页自动定位到答案文件。关联中图标高亮。',
        fields: ['答案字段关联图标', '解析字段关联图标'],
        states: [
          '默认态：标题后方显示关联图标',
          '关联中：图标高亮',
          '跨文件模式：点击后自动定位到答案文件',
        ],
      },
      operation: {
        title: '手动关联答案',
        description: '1、点击「答案」或「解析」后的关联图标，直接进入关联态。\n2、跨文件模式下自动定位到答案文件位置；无法定位到具体位置则定位到答案文件开始位置。\n3、用户在左侧框选内容后，识别结果自动填入对应答案/解析区域。\n4、框选时间时包含答案和解析，系统自动拆分并分别回显。\n【6.21】框选内容不符合当前答案/解析区域填写规则时，系统不写入内容，并提示「不符合答案解析填写规范，请重新框选或填写」。',
        permission: '无额外权限限制',
        dataFlow: '框选内容识别结果写入对应题目的答案/解析区域，加入试卷时随题目数据传递。',
        exceptions: '跨文件模式无法定位到具体位置时，定位到答案文件开始位置。【6.21】框选内容不符合当前答案/解析填写规范时，显示 toast「不符合答案解析填写规范，请重新框选或填写」，并保留原答案/解析内容。',
      },
      acceptance: [
        '答案和解析标题后方显示关联图标',
        '点击关联图标后直接进入关联答案状态',
        '跨文件模式点击关联图标后定位到答案文件',
        '框选内容识别后可自动拆分并回显到答案和解析区域',
        '【6.21】不符合填写规范的框选内容不应写入答案/解析区域，并应展示对应 toast 提示',
      ],
      source: { decisionFile, decisionObject: '答案关联icon / 6.21 需求评审异常场景', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-006',
      title: '图片模式与编辑模式切换',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.21',
      objectType: 'tab',
      objectName: '图片模式/编辑模式切换按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-view-mode',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-view-mode'),
      display: {
        title: '视图模式切换',
        description: '右侧面板顶部有「图片模式」和「编辑模式」两个切换按钮。图片模式显示题目截图，编辑模式显示识别文字并可编辑。编辑模式下显示提示「请注意甄别AI识别内容」。切换时有加载动画。【6.21】图片模式和编辑模式属于视图切换，切换时保留答案、解析和用户修改内容，不因视图切换清空。【6.21】顶层处于图片模式时，单题仍支持切换为编辑模式，系统识别为填空题时，首次呈现自动使用该题编辑模式。',
        fields: ['图片模式按钮', '编辑模式按钮', '请注意甄别AI识别内容', '【6.21】单题编辑模式切换', '【6.21】填空题图片模式提示'],
        states: [
          '图片模式选中：绿色高亮',
          '编辑模式选中：绿色高亮',
          '切换中：加载动画',
          '【6.21】顶层图片模式 + 单题编辑模式：该题显示编辑内容，其他题仍按顶层图片模式显示',
          '【6.21】填空题首次呈现：单题自动使用编辑模式',
        ],
      },
      operation: {
        title: '切换视图模式',
        description: '1、点击「图片模式」查看题目原始截图。\n2、点击「编辑模式」编辑识别文字、答案和解析。\n【6.21】3、图片模式和编辑模式只是视图切换，切换时不弹窗，答案、解析和用户修改内容全部保留。\n【6.21】4、顶层处于图片模式时，用户仍可对单题切换为编辑模式。\n【6.21】5、系统识别为填空题时，首次呈现自动使用该题编辑模式，用户手动切回图片模式后，在题型后显示「图片模式下暂不支持【填空题】，可切换至编辑模式处理」。\n【6.21】6、存在待更新识别结果时，用户点击「更新识别结果」并确认后，系统同时更新对应题目的图片内容和编辑模式内容。',
        permission: '无额外权限限制',
        dataFlow: '图片裁剪数据和编辑改动作为当前题目数据保留。【6.21】图片模式/编辑模式切换保留题目的图片、识别文字、答案、解析和用户修改内容，确认更新识别结果后，对应题目的图片内容和编辑模式内容替换为最新识别结果。',
        exceptions: '【6.21】没有待更新识别结果时，切换图片模式/编辑模式不触发内容替换，有待更新识别结果时，仅在用户确认更新识别结果后替换对应内容。',
      },
      acceptance: [
        '两种模式可切换',
        '切换有加载动画',
        '编辑模式可编辑内容',
        '图片模式显示截图',
        '【6.21】图片模式/编辑模式切换时，答案、解析和用户修改内容应保留',
        '【6.21】顶层图片模式下，单题应可切换为编辑模式',
        '【6.21】填空题首次呈现自动使用单题编辑模式，手动切回图片模式时展示填空题图片模式不支持提示',
        '【6.21】确认更新识别结果后，应同时替换对应题目的图片内容和编辑模式内容',
      ],
      source: { decisionFile, decisionObject: '图片模式/编辑模式 / 6.21 需求评审异常场景', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-007',
      title: '题目图片裁剪功能',
      sourceType: 'code',
      objectType: 'button',
      objectName: '裁剪按钮与裁剪操作',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-crop',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-crop'),
      display: {
        title: '题目图片裁剪',
        description: '编辑模式下提供「使用图片」开关，图片模式下提供裁剪按钮。裁剪模式下图片四周显示调整手柄，底部展示「取消」和「确认裁剪」按钮。已裁剪后可「还原」到用户在左侧框选的原始图片。',
        fields: ['使用图片开关', '裁剪按钮', '确认裁剪按钮', '取消按钮', '还原按钮'],
        states: [
          '未开启使用图片：显示识别文字',
          '裁剪模式：显示调整手柄和操作按钮',
          '已裁剪：可还原到左侧框选的原始图片',
        ],
      },
      operation: {
        title: '裁剪题目图片',
        description: '1、编辑模式下开启「使用图片」显示题目图片。\n2、点击裁剪按钮进入裁剪模式，拖动手柄调整范围。\n3、确认裁剪保存结果，取消退出裁剪模式。\n4、裁剪后可点击「还原」恢复到原始图片。',
        permission: '无额外权限限制',
        dataFlow: '裁剪结果保存到当前题目，加入试卷时随题目数据传递。',
        exceptions: '无异常场景',
      },
      acceptance: [
        '编辑模式下有使用图片开关',
        '图片模式下有裁剪按钮',
        '确认裁剪保存结果',
        '取消不保存',
        '可还原到用户在左侧框选的图片',
      ],
      source: { decisionFile, decisionObject: '裁剪功能', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-008',
      title: '加入试卷按钮',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.5',
      objectType: 'button',
      objectName: '加入试卷按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-add-to-paper-btn',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-add-to-paper-btn'),
      display: {
        title: '加入试卷按钮',
        description: '顶部步骤条右侧操作区，文案「加入试卷」。有题目时绿色可点击，无题目时置灰。',
        fields: ['加入试卷'],
        states: ['可用态：有题目（绿色可点击）', '禁用态：无题目（灰色）'],
      },
      operation: {
        title: '加入试卷',
        description: '1、点击后检查是否有未匹配答案或解析。\n2、有缺失时弹窗：「确认加入试卷吗？」「当前还有 X 道题的答案/解析没有补充，您可以在后续组卷页面使用AI批量补充功能，进行补充。」（一道大题存在答案或解析未匹配即计1道）。取消停留在步骤4，确认进入后续组卷页面。\n3、确认后完整保留父题、子题、子题答案/解析、填空空位答案、题型、选项数和题目图片传递给下游。\n4、加入试卷前保存当前状态，供从试卷编辑页返回时恢复。\n5、题目数据保存失败时停留在步骤4并提示：「加入试卷失败，题目数据暂未保存，请重试」。',
        permission: '无额外权限限制',
        dataFlow: '题目数据传递给试卷编辑页面，弹窗状态暂存供返回恢复。',
        exceptions: '有未匹配答案/解析时需弹窗二次确认。题目数据保存失败时阻断加入并提示。',
      },
      acceptance: [
        '有题目时按钮可用',
        '无题目时按钮置灰',
        '有答案或解析缺口时显示「确认加入试卷吗？」弹窗',
        '点击取消后停留在步骤4',
        '点击确认后进入后续组卷页面',
        '加入后数据完整传递',
        '题目数据保存失败时停留在核查页并显示失败提示',
      ],
      source: { decisionFile, decisionObject: '加入试卷', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-009',
      title: '识别失败降级处理',
      sourceType: 'code+decision',
      objectType: 'state',
      objectName: '识别失败降级状态',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-error-fallback',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-error-fallback'),
      display: {
        title: '识别失败处理',
        description: '生产环境识别失败时停留在框选阶段，不进入核对页面。显示「识别失败，请调整框选范围后重试」。',
        fields: ['识别失败提示'],
        states: ['识别失败：停留在框选阶段'],
      },
      operation: {
        title: '识别失败处理',
        description: '1、AI 识别失败时不生成模拟数据，不进入核查页面。\n2、用户可调整框选范围后重新识别。\n3、仅识别题目模式下框选区域包含答案/解析时，由用户在核查页面通过裁剪手动处理。',
        permission: '无额外权限限制',
        dataFlow: '无额外数据流转',
        exceptions: '识别失败时需用户手动重试。',
      },
      acceptance: [
        '识别失败停留在框选阶段',
        '显示错误提示',
        '不生成模拟数据',
        '可重试',
      ],
      source: { decisionFile, decisionObject: '识别失败降级', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-012',
      title: '核对识别结果步骤条回退确认',
      sourceType: 'code',
      objectType: 'step',
      objectName: '步骤条回退确认',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-single-mode-back',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-single-mode-back'),
      display: {
        title: '步骤条回退',
        description: '步骤4中，第1步「上传资料」、第2步「选择识别方式」、第3步「选择识别内容」为可点击回退节点，第4步为当前激活态（绿色高亮）。点击前三步时分别弹出对应确认弹窗。',
        fields: ['步骤条第1步', '步骤条第2步', '步骤条第3步', '步骤条第4步'],
        states: [
          '第1步：可点击，弹出确认更换资料弹窗',
          '第2步：可点击，弹出确认更换识别方式弹窗',
          '第3步：可点击，弹出确认重新选择识别内容弹窗',
          '第4步：绿色高亮当前激活态',
        ],
      },
      operation: {
        title: '回退到前面步骤',
        description: '1、点击「上传资料」→ 弹窗「确认更换资料吗？」「更换资料将清空当前的识别结果。」\n2、点击「选择识别方式」→ 弹窗「确认更换识别方式吗？」「更换识别方式将清空当前的识别结果。」\n3、点击「选择识别内容」→ 弹窗「确认重新选择识别内容吗？」「重新选择识别内容将清空当前识别结果，并恢复进入步骤4之前框选的题目框。」\n4、三个弹窗均为：取消留在步骤4，确认返回对应步骤。',
        permission: '无额外权限限制',
        dataFlow: '确认后按对应回退动作清空识别结果，取消则不清空。回退到步骤3时，回显进入步骤4之前的框选状态，而非进入步骤3时的初始框。',
        exceptions: '未确认前不得离开步骤4。',
      },
      acceptance: [
        '点击步骤1应显示确认更换资料弹窗',
        '点击步骤2应显示确认更换识别方式弹窗',
        '点击步骤3应显示确认重新选择识别内容弹窗',
        '三个弹窗点击取消后均停留在步骤4',
        '三个弹窗点击确认后均返回对应步骤条位置',
      ],
      source: { decisionFile, decisionObject: '步骤条回退确认', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-013',
      title: '题目卡片排序功能移除',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.21',
      objectType: 'button',
      objectName: '题目卡片排序功能',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-question-reorder',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-question-reorder'),
      display: {
        title: '题目卡片排序能力移除',
        description: '本期移除题目卡片拖动排序功能。题目顺序按识别结果和左侧资料题号顺序展示，上移和下移操作保留。【6.21】右侧题卡不按文件名或页码分组展示，不显示文件名/页码分组标题。',
        fields: ['拖动题目顺序功能', '上移题目按钮', '下移题目按钮', '【6.21】新增框插入位置', '【6.21】不显示文件名页码分组'],
        states: [
          '本期移除：不展示拖动排序入口，保留上移下移',
          '题目顺序：按识别结果和左侧资料题号顺序展示',
          '【6.21】新增框插入：以新增框上方已有框对应的右侧题卡为锚点，新题卡显示在该锚点题卡下方',
          '【6.21】右侧列表：不展示文件名/页码分组',
        ],
      },
      operation: {
        title: '题目顺序调整',
        description: '1、本期不支持拖动调整题目顺序。仅支持上移或下移调整题目顺序。\n2、加入试卷时按当前核对列表顺序传递。\n【6.21】3、用户在左侧新增框后，右侧新题卡以新增框上方已有框对应的右侧题卡为锚点插入，显示在该锚点题卡下方，如果右侧题卡曾被上移/下移调整顺序，也按调整后的右侧位置插入。\n【6.21】4、右侧题卡列表不按文件名或页码分组。',
        permission: '无额外权限限制',
        dataFlow: '题目顺序按当前列表顺序传递。【6.21】新增题卡插入位置根据新增框上方已有框与右侧题卡的当前对应关系计算，右侧手动排序结果参与插入位置判断。',
        exceptions: '顺序不符合预期时需返回选择识别内容重新框选或重新识别。【6.21】文件名/页码不作为题卡分组展示依据。',
      },
      acceptance: [
        '题目卡片不展示拖动排序入口',
        '题目卡片保留上移和下移按钮',
        '裁剪功能可用时不与题目排序功能冲突',
        '加入试卷按当前核对列表顺序传递题目',
        '【6.21】左侧新增框后，新题卡应显示在新增框上方已有框对应的右侧题卡下方',
        '【6.21】右侧题卡不应展示文件名/页码分组标题',
      ],
      source: { decisionFile, decisionObject: '题目卡片排序操作 / 6.21 需求评审异常场景', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-014',
      title: '删除题目卡片',
      sourceType: 'code',
      objectType: 'button',
      objectName: '题目卡片删除按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-question-delete',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-question-delete'),
      display: {
        title: '题目卡片删除按钮',
        description: '每张题目卡片头部右侧显示删除图标按钮，默认为灰色，悬停时红色强调并显示「删除题目」提示。',
        fields: ['删除题目按钮', '删除题目提示'],
        states: ['默认态：灰色', '悬停态：红色强调'],
      },
      operation: {
        title: '删除题目',
        description: '1、点击删除后题目卡片从列表移除。\n2、被删除题目的全部内容不再加入试卷。',
        permission: '无额外权限限制',
        dataFlow: '删除后题目不再传递给试卷编辑页面。',
        exceptions: '不提供二次确认和撤销入口，误删后需重新识别或补录。',
      },
      acceptance: [
        '点击删除后题目卡片从列表消失',
        '删除后的题目不加入试卷',
        '删除按钮悬停时有明显红色反馈',
      ],
      source: { decisionFile, decisionObject: '题目卡片删除操作', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-015',
      title: '题目卡片排序（题目+答案模式）',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.21',
      objectType: 'button',
      objectName: '题目+答案模式题目卡片上移/下移按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-question-reorder-stepwise',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-question-reorder-stepwise'),
      display: {
        title: '题目+答案模式下的题目卡片排序',
        description: '题目+答案模式下，题目卡片提供上移、下移操作图标，不提供拖动排序。首题上移置灰，末题下移置灰。【6.21】右侧题卡不按文件名或页码分组展示，不显示文件名/页码分组标题。',
        fields: ['上移题目按钮', '下移题目按钮', '【6.21】新增框插入位置', '【6.21】不显示文件名页码分组'],
        states: [
          '第一张题目：上移置灰',
          '最后一张题目：下移置灰',
          '中间题目：上移和下移均可',
          '【6.21】新增框插入：以新增框上方已有框对应的右侧题卡为锚点，新题卡显示在该锚点题卡下方',
          '【6.21】右侧列表：不展示文件名/页码分组',
        ],
      },
      operation: {
        title: '调整题目顺序',
        description: '1、仅通过上移、下移调整题目顺序，不支持拖拽。\n2、加入试卷时按当前右侧最终顺序传递。\n【6.21】3、用户在左侧新增框后，右侧新题卡以新增框上方已有框对应的右侧题卡为锚点插入，显示在该锚点题卡下方，如果右侧题卡曾被上移/下移调整顺序，也按调整后的右侧位置插入。\n【6.21】4、右侧题卡列表不按文件名或页码分组。',
        permission: '无额外权限限制',
        dataFlow: '排序结果保存在当前列表中，加入试卷时按最终顺序传递。【6.21】新增题卡插入位置根据新增框上方已有框与右侧题卡的当前对应关系计算，右侧手动排序结果参与插入位置判断。',
        exceptions: '边界题目不可继续向对应方向移动。【6.21】文件名/页码不作为题卡分组展示依据。',
      },
      acceptance: [
        '题目卡片展示上移和下移操作图标',
        '题目卡片不展示拖动排序入口',
        '用户只能通过上移、下移改变题目顺序',
        '裁剪功能可用时不与题目排序功能冲突',
        '加入试卷按当前右侧最终顺序传递题目、答案和解析',
        '【6.21】左侧新增框后，新题卡应显示在新增框上方已有框对应的右侧题卡下方',
        '【6.21】右侧题卡不应展示文件名/页码分组标题',
      ],
      source: { decisionFile, decisionObject: '题目+答案模式题目卡片排序操作 / 6.21 需求评审异常场景', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-016',
      title: '删除题目卡片（题目+答案模式）',
      sourceType: 'code',
      objectType: 'button',
      objectName: '题目+答案模式题目卡片删除按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-question-delete-stepwise',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-question-delete-stepwise'),
      display: {
        title: '题目+答案模式下的删除按钮',
        description: '每张题目卡片头部右侧显示删除图标按钮，默认为灰色，悬停时红色强调并显示「删除题目」提示。',
        fields: ['删除题目按钮', '删除题目提示'],
        states: ['默认态：灰色', '悬停态：红色强调'],
      },
      operation: {
        title: '删除题目',
        description: '1、点击删除后题目卡片从列表移除。\n2、被删除题目的全部内容不再加入试卷。',
        permission: '无额外权限限制',
        dataFlow: '删除后题目、答案和解析不再传递给试卷编辑页面。',
        exceptions: '不提供二次确认和撤销入口，误删后需重新识别或补录。',
      },
      acceptance: [
        '点击删除后题目卡片从列表消失',
        '删除后的题目不加入试卷',
        '删除按钮悬停时有明显红色反馈',
      ],
      source: { decisionFile, decisionObject: '题目+答案模式题目卡片删除操作', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-017',
      title: '题型切换结构保护',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '6.5',
      objectType: 'dialog',
      objectName: '切换题型确认弹窗',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-question-type-guard',
      anchorStatus: 'planned',
      activate: activateReview('review-step-question-type-guard'),
      display: {
        title: '切换题型确认',
        description: '题目已有子题、扩展选项、多空答案、答案或解析时，切换题型前显示确认弹窗：「确认切换题型吗？」「切换题型将调整题目结构，可能清空子题的答案及解析」。无结构化内容时直接切换。',
        fields: ['题型选择器', '切换题型确认弹窗', '确认按钮', '取消按钮'],
        states: ['无结构化内容：直接切换', '已有结构化内容：弹窗确认', '取消：保持原题型', '确认：按新题型调整结构'],
      },
      operation: {
        title: '切换题型',
        description: '1、选择新题型后，系统判断是否有子题、扩展选项、多空答案、答案或解析。\n2、有以上内容时先弹窗确认，无则直接切换。\n3、取消保持原题型和原内容，确认后切换并按新题型调整结构。',
        permission: '无额外权限限制',
        dataFlow: '切换后的题型和结构化内容随题目数据传递给试卷编辑页面。',
        exceptions: '已有结构化内容时必须先确认，避免误切题型导致子题内容清空。',
      },
      acceptance: [
        '无结构化内容时可直接切换题型',
        '已有子题、扩展选项、多空答案、答案或解析时先显示确认弹窗',
        '取消后题型和内容不变',
        '确认后才按新题型调整结构',
        '确认弹窗文案与决策一致',
      ],
      source: { decisionFile, decisionObject: '切换题型时已有结构化内容的保护规则', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-018',
      title: '答案解析清空操作',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '6.5',
      objectType: 'button',
      objectName: '答案/解析清空按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-answer-clear',
      anchorStatus: 'planned',
      activate: activateReview('review-step-answer-clear'),
      display: {
        title: '答案解析清空按钮',
        description: '题目卡片和子题区域中有答案、解析或空位答案时，显示对应清空入口（答案区「清空」、解析区「清空」、空位清空图标、子题清空图标）。无内容时隐藏。',
        fields: ['清空答案', '清空解析', '空位答案清空图标', '子题答案清空图标', '子题解析清空图标'],
        states: ['有内容：显示清空入口', '无内容：隐藏清空入口'],
      },
      operation: {
        title: '清空答案解析',
        description: '1、点击清空入口后立即清除对应内容，不弹二次确认。\n2、清空后匹配状态按剩余内容重新计算。',
        permission: '无额外权限限制',
        dataFlow: '清空后的内容保存在当前列表中，加入试卷时按清空后内容传递。',
        exceptions: '不提供撤销入口；误清空需重新输入或重新框选。',
      },
      acceptance: [
        '有内容时显示对应清空入口',
        '无内容时隐藏对应清空入口',
        '点击清空后立即清除对应内容',
        '清空时不弹出二次确认',
        '清空后匹配状态按最新内容更新',
      ],
      source: { decisionFile, decisionObject: '清空答案、解析和空位答案的保护规则', relatedFiles },
    },
  ],
  excludedDecisions: [
    {
      objectName: '解答题答案/解析自动分发规则中的不可拆分情况',
      reason: '已纳入 REVIEW_STEP-004 的异常处理中',
      sourceDecision: '决策 3',
    },
  ],
};
