import type { RequirementRegistry } from './schema';

const relatedFiles = [
  'src/components/UploadQuestionDialog.tsx',
  'src/app/homework/page.tsx',
  'src/app/api/recognize-questions/route.ts',
  'src/lib/ai-recognizer.ts',
  'src/app/paper-edit/page.tsx',
];
const decisionFile = 'docs/prd-workflow/decisions/question-answer-review-step.decision.md';
const tabletReviewDecisionFile = '产品文档/prd-workflow/decisions/question-answer-review-step.decision.md';
const tabletReviewRelatedFiles = [
  'src/app/tablet-ai-entry/tablet-ai-entry-preview.tsx',
  'src/app/tablet-ai-entry/page.tsx',
  'src/requirements/question-answer-review-step.registry.ts',
  tabletReviewDecisionFile,
];
const tabletReviewRecognitionRelatedFiles = [
  ...tabletReviewRelatedFiles,
  'src/components/UploadQuestionDialog.tsx',
];
const tabletReviewQaImageRelatedFiles = [
  ...tabletReviewRelatedFiles,
  'src/components/UploadQuestionDialog.tsx',
  'src/app/homework/page.tsx',
  'src/app/api/recognize-questions/route.ts',
  'src/lib/ai-recognizer.ts',
  'src/app/paper-edit/page.tsx',
  '产品文档/prd-workflow/inventories/tablet-review-question-answer-image-mode.inventory.md',
];

const pageName = '核对识别结果';
const route = '/homework → 识别作业资料 → 核对识别结果';
const moduleName = '识别作业资料';
const tabletReviewRecognitionModuleName = '仅题目模式 / 识别模式';
const tabletReviewQaImageModuleName = '题目+答案模式 / 图片模式';
const tabletReviewQaRecognitionModuleName = '题目+答案模式 / 识别模式';

function activateReview(anchorId: string) {
  return [
    { type: 'openDialog' as const, label: '打开识别作业资料弹窗', dialog: 'UploadQuestionDialog' },
    { type: 'setStep' as const, label: '切换到核对识别结果步骤', step: 'review' },
    { type: 'scrollTo' as const, label: '定位页面对象', anchorId },
    { type: 'highlight' as const, label: '高亮页面对象', anchorId },
  ];
}

function activateTabletReviewRecognition(anchorId: string) {
  return [
    { type: 'navigate' as const, label: '打开平板端入口', to: '/tablet-ai-entry' },
    { type: 'setStep' as const, label: '切换到核对识别结果步骤', step: 'review' },
    { type: 'setTab' as const, label: '切换到识别模式', tab: 'recognition' },
    { type: 'scrollTo' as const, label: '定位识别模式对象', anchorId },
    { type: 'highlight' as const, label: '高亮识别模式对象', anchorId },
  ];
}

function activateTabletReviewQaImage(anchorId: string) {
  return [
    { type: 'navigate' as const, label: '打开平板端入口', to: '/tablet-ai-entry' },
    { type: 'setStep' as const, label: '切换到核对识别结果步骤', step: 'review' },
    { type: 'setTab' as const, label: '切换到图片模式', tab: 'image' },
    { type: 'scrollTo' as const, label: '定位题目+答案图片模式对象', anchorId },
    { type: 'highlight' as const, label: '高亮题目+答案图片模式对象', anchorId },
  ];
}

function activateTabletReviewQaRecognition(anchorId: string) {
  return [
    { type: 'navigate' as const, label: '打开平板端入口', to: '/tablet-ai-entry' },
    { type: 'setStep' as const, label: '切换到核对识别结果步骤', step: 'review' },
    { type: 'setTab' as const, label: '切换到识别模式', tab: 'recognition' },
    { type: 'scrollTo' as const, label: '定位题目+答案识别模式对象', anchorId },
    { type: 'highlight' as const, label: '高亮题目+答案识别模式对象', anchorId },
  ];
}

export const questionAnswerReviewStepRegistry: RequirementRegistry = {
  registryId: 'question-answer-review-step',
  pageName,
  route,
  module: moduleName,
  description: '记录步骤 4「核对识别结果」的完整页面逻辑，覆盖匹配状态提示、题目卡片展示、题目卡片排序与删除、子题结构与编辑、答案/解析核对与关联、题型切换保护、图片模式与编辑模式切换、加入试卷等交互边界。',
  sourceDecisionFile: decisionFile,
  relatedFiles,
  requirements: [
    {
      id: 'REVIEW_STEP-001',
      title: '匹配状态提示（分步模式）',
      sourceType: 'code+decision',
      objectType: 'region',
      objectName: '匹配状态提示条',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-match-banner',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-match-banner'),
      display: {
        title: '匹配状态提示',
        description: '题目+答案模式下，右侧面板顶部显示匹配状态提示条。存在待匹配题目时：「识别结果：共 X 道题目，已匹配答案 Y 题，待匹配答案 N 题（待匹配答案的题目，可在左侧框选答案/解析手动关联题目）」。全部匹配后：「全部题目已匹配答案和解析，可将题目加入试卷了~」。提示条始终完整展示，不可收起或展开。',
        fields: ['父题数量', '已匹配答案数量', '待匹配答案数量'],
        states: ['存在待匹配题目', '全部匹配'],
      },
      operation: {
        title: '查看匹配进度',
        description: '提示条不可点击、不可收起、不可展开。存在待匹配题目时，用户可通过左侧框选答案/解析手动关联。',
        permission: '无额外权限限制',
        dataFlow: '匹配统计根据已识别的题目、答案和解析数据计算。',
        exceptions: '没有识别结果时不展示。',
      },
      acceptance: [
        '存在待匹配题目时，提示条正确显示识别结果统计',
        '待匹配数量正确',
        '全部题目均已匹配答案/解析时，提示条显示「全部题目已匹配答案和解析，可将题目加入试卷了~」',
      ],
      source: { decisionFile, decisionObject: '答案匹配状态与统计', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-002',
      title: '题目卡片展示（仅识别题目模式）',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.21',
      objectType: 'region',
      objectName: '题目卡片（仅识别题目模式）',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-question-card-single',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-question-card-single'),
      display: {
        title: '仅识别题目模式下的题目卡片',
        description: '仅识别题目模式下，右侧按题号展示每道题目。题号顺序以左侧资料页为准；补识别新增题按题号插入已有题目之间；重识别同题号题干时原位置覆盖。每张卡片含题号、题型、题目内容和图片预览，不展示答案/解析区域。【6.21】系统识别为填空题时，首次呈现自动使用该题编辑模式，如果用户手动切回图片模式，题型后显示提示「图片模式下暂不支持【填空题】，可切换至编辑模式处理」。【6.21】系统识别为断句题时，题型兜底显示为问答题，并在题型后显示提示「系统暂不支持【断句题】，建议用问答题题型替代」。',
        fields: ['题号', '题型', '题目内容', '图片预览', '【6.21】填空题图片模式提示', '【6.21】断句题兜底提示'],
        states: [
          '图片模式：显示截图',
          '编辑模式：显示识别文字',
          '新增题：按题号插入',
          '重识别题：原位置覆盖',
          '【6.21】填空题首次呈现：单题自动使用编辑模式',
          '【6.21】断句题：题型显示为问答题并展示断句题不支持提示',
        ],
      },
      operation: {
        title: '核对与编辑',
        description: '1、可切换图片模式查看截图或编辑模式修改文字。\n2、两种模式下均可修改题型。\n3、点击左侧题号框可定位到右侧对应题目，点击右侧题号可定位到左侧对应资料位置。\n4、编辑模式下可修改题目内容。\n5、可使用裁剪功能截取题目图片。\n6、可为复合题添加子题。\n7、补识别新增题：左侧框选漏掉题干后点击开始识别，新题卡按题号插入。\n8、重识别已有题：重新框选完整题干后点击开始识别，原题卡覆盖更新。\n【6.21】对已识别选框调整后点击「更新识别结果」，右侧采用覆盖当前对应题卡的方式处理，不按新增题卡处理。',
        permission: '无额外权限限制',
        dataFlow: '题目数据来源于 AI 识别结果。新增题按题号插入，重识别同题号覆盖原题卡。用户编辑后更新本地状态，加入试卷时传递给下游。',
        exceptions: '识别失败时停留在框选阶段。',
      },
      acceptance: [
        '题目卡片正确展示',
        '右侧题号顺序应以左侧资料页题号顺序为准',
        '点击左侧题号框时右侧自动定位到对应题目',
        '单击右侧题号时左侧自动定位到对应资料位置',
        '图片/编辑模式可切换',
        '题型和内容可编辑',
        '裁剪功能可用',
        '第4步补识别新增题后应按题号插入列表',
        '第4步重识别重复题后应原位置覆盖',
        '【6.21】调整已识别选框后更新识别结果，应覆盖当前对应题卡而不是新增题卡',
        '【6.21】填空题首次呈现自动使用单题编辑模式，手动切回图片模式时展示填空题图片模式不支持提示',
        '【6.21】断句题兜底显示为问答题，并展示断句题不支持提示',
      ],
      source: { decisionFile, decisionObject: '仅识别题目模式展示 / 6.21 需求评审异常场景', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-003',
      title: '题目卡片展示（识别题目和答案模式）',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.21',
      objectType: 'region',
      objectName: '题目卡片（识别题目和答案模式）',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-question-card-stepwise',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-question-card-stepwise'),
      display: {
        title: '题目+答案模式下的题目卡片',
        description: '题目+答案模式下，右侧按题号展示每道题目。题号顺序以左侧资料页为准。每张卡片含题号、题型、题目内容、答案区域和解析区域。匹配状态用四种标签区分：「答案解析已匹配」「未匹配到答案」「未匹配到解析」「未匹配到答案和解析」。填空题按空位展示答案，解答题按子题结构展示子题答案和解析。补识别新增题按题号插入，重识别同题号题干时原位置覆盖。【6.21】系统识别为填空题时，首次呈现自动使用该题编辑模式，如果用户手动切回图片模式，题型后显示提示「图片模式下暂不支持【填空题】，可切换至编辑模式处理」。【6.21】系统识别为断句题时，题型兜底显示为问答题，并在题型后显示提示「系统暂不支持【断句题】，建议用问答题题型替代」。',
        fields: ['题号', '题型', '题目内容', '答案', '解析', '匹配状态标签', '子题答案/解析', '【6.21】填空题图片模式提示', '【6.21】断句题兜底提示'],
        states: [
          '答案和解析均匹配：显示「答案解析已匹配」',
          '未匹配到答案：显示「未匹配到答案」',
          '未匹配到解析：显示「未匹配到解析」',
          '未匹配到答案和解析：显示「未匹配到答案和解析」',
          '四种标签样式有区分',
          '图片模式：显示截图',
          '编辑模式：显示识别文字',
          '新增题：按题号插入',
          '重识别题：原位置覆盖',
          '【6.21】填空题首次呈现：单题自动使用编辑模式',
          '【6.21】断句题：题型显示为问答题并展示断句题不支持提示',
        ],
      },
      operation: {
        title: '核对与编辑',
        description: '1、可切换图片模式查看截图或编辑模式修改文字。\n2、两种模式下均可修改题型、编辑答案和解析。\n3、点击左侧题号框可定位到右侧对应题目，点击右侧题号可定位到左侧对应资料位置。\n4、编辑模式下可修改题目内容。\n5、可使用裁剪功能截取题目图片。\n6、可为复合题添加子题。\n7、未匹配答案时，可通过再次框选并点击开始识别更新结果；也可点击【答案】【解析】后的关联图标进入关联态，跨文件模式下自动定位到答案文件位置，无法定位到具体位置则定位到答案文件开始位置。\n8、补识别新增题：左侧框选漏掉题干后点击开始识别，新题卡按题号插入。\n9、重识别已有题：重新框选完整题干后点击开始识别，原题卡覆盖更新。\n【6.21】对已识别选框调整后点击「更新识别结果」，右侧采用覆盖当前对应题卡的方式处理，不按新增题卡处理。',
        permission: '无额外权限限制',
        dataFlow: '题目数据来源于 AI 识别和答案匹配结果。新增题按题号插入，重识别同题号覆盖原题卡。用户编辑后更新本地状态，加入试卷时传递给下游。',
        exceptions: '识别失败时停留在框选阶段。',
      },
      acceptance: [
        '题目卡片含答案和解析区域',
        '右侧题号顺序应以左侧资料页题号顺序为准',
        '四种答案/解析匹配状态标签正确显示且样式有区分',
        '点击左侧题号框时右侧自动定位到对应题目',
        '单击右侧题号时左侧自动定位到对应资料位置',
        '未匹配答案时可通过再次框选并开始识别更新结果',
        '答案/解析关联图标可引导用户定位答案文件并进入关联状态',
        '填空题按空位显示答案',
        '解答题显示子题结构',
        '图片/编辑模式可切换',
        '第4步补识别新增题后应按题号插入列表',
        '第4步重识别重复题后应原位置覆盖',
        '【6.21】调整已识别选框后更新识别结果，应覆盖当前对应题卡而不是新增题卡',
        '【6.21】填空题首次呈现自动使用单题编辑模式，手动切回图片模式时展示填空题图片模式不支持提示',
        '【6.21】断句题兜底显示为问答题，并展示断句题不支持提示',
      ],
      source: { decisionFile, decisionObject: '题目+答案模式展示 / 6.21 需求评审异常场景', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-004',
      title: '子题结构与编辑',
      sourceType: 'code+decision',
      objectType: 'region',
      objectName: '子题结构区域',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-subquestion',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-subquestion'),
      display: {
        title: '子题结构',
        description: '复合题型（解答题、完形填空、阅读理解等）支持子题结构。识别时系统自动拆分大题的子题，右侧展示时已添加好子题，每个子题含序号（①②③...）、自动匹配的题型、答案和解析区域。父题无需显示子题匹配进度标签。乐课网资源库中无子题的大题不显示【+子题】按钮。',
        fields: ['子题序号', '子题题型', '子题答案', '子题解析', '+子题按钮', '删除子题按钮'],
        states: [
          '资源库无子题的大题：不显示【+子题】',
          '新增子题：空子题',
          '无法拆分答案/解析：父题区显示「答案解析待人工拆分」',
          '已手动拆分：隐藏「答案解析待人工拆分」标签',
          '删除子题确认弹窗',
        ],
      },
      operation: {
        title: '子题编辑',
        description: '1、题干子题标记≥2时系统自动生成子题结构。\n2、子题题型根据题干要求自动匹配，不固定继承父题。\n3、子题题型可选项根据菁优网的题型显示。\n4、答案/解析按子题标记自动拆分；无法拆分时保留在父题区并显示「答案解析待人工拆分」，手动拆分后标签隐藏。\n5、资源库无子题的大题不显示【+子题】。\n6、点击「+子题」新增空子题。\n7、删除有内容的子题时弹窗确认：「该子题已有答案/解析，删除后内容将一并移除，是否继续？」',
        permission: '无额外权限限制',
        dataFlow: '子题数据作为题目数据的一部分，加入试卷时保留完整子题结构。',
        exceptions: '题干少于2个子题标记时不自动生成子题结构。',
      },
      acceptance: [
        '子题自动拆分正确',
        '子题题型自动匹配',
        '无法拆分时显示「答案解析待人工拆分」标签',
        '手动拆分答案与解析后隐藏「答案解析待人工拆分」标签',
        '资源库无子题的大题不显示【+子题】按钮',
        '新增子题为空',
        '删除有内容的子题弹窗确认',
        '加入试卷保留子题结构',
      ],
      source: { decisionFile, decisionObject: '子题结构与编辑', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-005',
      title: '答案关联icon',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.21',
      objectType: 'button',
      objectName: '答案/解析关联图标',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-answer-link-icon',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-answer-link-icon'),
      display: {
        title: '答案关联icon',
        description: '每道题的「答案」「解析」标题后方显示轻量关联图标。跨文件模式下点击后左侧资料页自动定位到答案文件。关联中图标高亮。',
        fields: ['答案字段关联图标', '解析字段关联图标'],
        states: [
          '默认态：标题后方显示关联图标',
          '关联中：图标高亮',
          '跨文件模式：点击后自动定位到答案文件',
        ],
      },
      operation: {
        title: '手动关联答案',
        description: '1、点击「答案」或「解析」后的关联图标，直接进入关联态。\n2、跨文件模式下自动定位到答案文件位置；无法定位到具体位置则定位到答案文件开始位置。\n3、用户在左侧框选内容后，识别结果自动填入对应答案/解析区域。\n4、框选时间时包含答案和解析，系统自动拆分并分别回显。\n【6.21】框选内容不符合当前答案/解析区域填写规则时，系统不写入内容，并提示「不符合答案解析填写规范，请重新框选或填写」。',
        permission: '无额外权限限制',
        dataFlow: '框选内容识别结果写入对应题目的答案/解析区域，加入试卷时随题目数据传递。',
        exceptions: '跨文件模式无法定位到具体位置时，定位到答案文件开始位置。【6.21】框选内容不符合当前答案/解析填写规范时，显示 toast「不符合答案解析填写规范，请重新框选或填写」，并保留原答案/解析内容。',
      },
      acceptance: [
        '答案和解析标题后方显示关联图标',
        '点击关联图标后直接进入关联答案状态',
        '跨文件模式点击关联图标后定位到答案文件',
        '框选内容识别后可自动拆分并回显到答案和解析区域',
        '【6.21】不符合填写规范的框选内容不应写入答案/解析区域，并应展示对应 toast 提示',
      ],
      source: { decisionFile, decisionObject: '答案关联icon / 6.21 需求评审异常场景', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-006',
      title: '图片模式与编辑模式切换',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.21',
      objectType: 'tab',
      objectName: '图片模式/编辑模式切换按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-view-mode',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-view-mode'),
      display: {
        title: '视图模式切换',
        description: '右侧面板顶部有「图片模式」和「编辑模式」两个切换按钮。图片模式显示题目截图，编辑模式显示识别文字并可编辑。编辑模式下显示提示「请注意甄别AI识别内容」。切换时有加载动画。【6.21】图片模式和编辑模式属于视图切换，切换时保留答案、解析和用户修改内容，不因视图切换清空。【6.21】顶层处于图片模式时，单题仍支持切换为编辑模式，系统识别为填空题时，首次呈现自动使用该题编辑模式。',
        fields: ['图片模式按钮', '编辑模式按钮', '请注意甄别AI识别内容', '【6.21】单题编辑模式切换', '【6.21】填空题图片模式提示'],
        states: [
          '图片模式选中：绿色高亮',
          '编辑模式选中：绿色高亮',
          '切换中：加载动画',
          '【6.21】顶层图片模式 + 单题编辑模式：该题显示编辑内容，其他题仍按顶层图片模式显示',
          '【6.21】填空题首次呈现：单题自动使用编辑模式',
        ],
      },
      operation: {
        title: '切换视图模式',
        description: '1、点击「图片模式」查看题目原始截图。\n2、点击「编辑模式」编辑识别文字、答案和解析。\n【6.21】3、图片模式和编辑模式只是视图切换，切换时不弹窗，答案、解析和用户修改内容全部保留。\n【6.21】4、顶层处于图片模式时，用户仍可对单题切换为编辑模式。\n【6.21】5、系统识别为填空题时，首次呈现自动使用该题编辑模式，用户手动切回图片模式后，在题型后显示「图片模式下暂不支持【填空题】，可切换至编辑模式处理」。\n【6.21】6、存在待更新识别结果时，用户点击「更新识别结果」并确认后，系统同时更新对应题目的图片内容和编辑模式内容。',
        permission: '无额外权限限制',
        dataFlow: '图片裁剪数据和编辑改动作为当前题目数据保留。【6.21】图片模式/编辑模式切换保留题目的图片、识别文字、答案、解析和用户修改内容，确认更新识别结果后，对应题目的图片内容和编辑模式内容替换为最新识别结果。',
        exceptions: '【6.21】没有待更新识别结果时，切换图片模式/编辑模式不触发内容替换，有待更新识别结果时，仅在用户确认更新识别结果后替换对应内容。',
      },
      acceptance: [
        '两种模式可切换',
        '切换有加载动画',
        '编辑模式可编辑内容',
        '图片模式显示截图',
        '【6.21】图片模式/编辑模式切换时，答案、解析和用户修改内容应保留',
        '【6.21】顶层图片模式下，单题应可切换为编辑模式',
        '【6.21】填空题首次呈现自动使用单题编辑模式，手动切回图片模式时展示填空题图片模式不支持提示',
        '【6.21】确认更新识别结果后，应同时替换对应题目的图片内容和编辑模式内容',
      ],
      source: { decisionFile, decisionObject: '图片模式/编辑模式 / 6.21 需求评审异常场景', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-007',
      title: '题目图片裁剪功能',
      sourceType: 'code',
      objectType: 'button',
      objectName: '裁剪按钮与裁剪操作',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-crop',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-crop'),
      display: {
        title: '题目图片裁剪',
        description: '编辑模式下提供「使用图片」开关，图片模式下提供裁剪按钮。裁剪模式下图片四周显示调整手柄，底部展示「取消」和「确认裁剪」按钮。已裁剪后可「还原」到用户在左侧框选的原始图片。',
        fields: ['使用图片开关', '裁剪按钮', '确认裁剪按钮', '取消按钮', '还原按钮'],
        states: [
          '未开启使用图片：显示识别文字',
          '裁剪模式：显示调整手柄和操作按钮',
          '已裁剪：可还原到左侧框选的原始图片',
        ],
      },
      operation: {
        title: '裁剪题目图片',
        description: '1、编辑模式下开启「使用图片」显示题目图片。\n2、点击裁剪按钮进入裁剪模式，拖动手柄调整范围。\n3、确认裁剪保存结果，取消退出裁剪模式。\n4、裁剪后可点击「还原」恢复到原始图片。',
        permission: '无额外权限限制',
        dataFlow: '裁剪结果保存到当前题目，加入试卷时随题目数据传递。',
        exceptions: '无异常场景',
      },
      acceptance: [
        '编辑模式下有使用图片开关',
        '图片模式下有裁剪按钮',
        '确认裁剪保存结果',
        '取消不保存',
        '可还原到用户在左侧框选的图片',
      ],
      source: { decisionFile, decisionObject: '裁剪功能', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-008',
      title: '加入试卷按钮',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.5',
      objectType: 'button',
      objectName: '加入试卷按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-add-to-paper-btn',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-add-to-paper-btn'),
      display: {
        title: '加入试卷按钮',
        description: '顶部步骤条右侧操作区，文案「加入试卷」。有题目时绿色可点击，无题目时置灰。',
        fields: ['加入试卷'],
        states: ['可用态：有题目（绿色可点击）', '禁用态：无题目（灰色）'],
      },
      operation: {
        title: '加入试卷',
        description: '1、点击后检查是否有未匹配答案或解析。\n2、有缺失时弹窗：「确认加入试卷吗？」「当前还有 X 道题的答案/解析没有补充，您可以在后续组卷页面使用AI批量补充功能，进行补充。」（一道大题存在答案或解析未匹配即计1道）。取消停留在步骤4，确认进入后续组卷页面。\n3、确认后完整保留父题、子题、子题答案/解析、填空空位答案、题型、选项数和题目图片传递给下游。\n4、加入试卷前保存当前状态，供从试卷编辑页返回时恢复。\n5、题目数据保存失败时停留在步骤4并提示：「加入试卷失败，题目数据暂未保存，请重试」。',
        permission: '无额外权限限制',
        dataFlow: '题目数据传递给试卷编辑页面，弹窗状态暂存供返回恢复。',
        exceptions: '有未匹配答案/解析时需弹窗二次确认。题目数据保存失败时阻断加入并提示。',
      },
      acceptance: [
        '有题目时按钮可用',
        '无题目时按钮置灰',
        '有答案或解析缺口时显示「确认加入试卷吗？」弹窗',
        '点击取消后停留在步骤4',
        '点击确认后进入后续组卷页面',
        '加入后数据完整传递',
        '题目数据保存失败时停留在核查页并显示失败提示',
      ],
      source: { decisionFile, decisionObject: '加入试卷', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-009',
      title: '识别失败降级处理',
      sourceType: 'code+decision',
      objectType: 'state',
      objectName: '识别失败降级状态',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-error-fallback',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-error-fallback'),
      display: {
        title: '识别失败处理',
        description: '生产环境识别失败时停留在框选阶段，不进入核对页面。显示「识别失败，请调整框选范围后重试」。',
        fields: ['识别失败提示'],
        states: ['识别失败：停留在框选阶段'],
      },
      operation: {
        title: '识别失败处理',
        description: '1、AI 识别失败时不生成模拟数据，不进入核查页面。\n2、用户可调整框选范围后重新识别。\n3、仅识别题目模式下框选区域包含答案/解析时，由用户在核查页面通过裁剪手动处理。',
        permission: '无额外权限限制',
        dataFlow: '无额外数据流转',
        exceptions: '识别失败时需用户手动重试。',
      },
      acceptance: [
        '识别失败停留在框选阶段',
        '显示错误提示',
        '不生成模拟数据',
        '可重试',
      ],
      source: { decisionFile, decisionObject: '识别失败降级', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-012',
      title: '核对识别结果步骤条回退确认',
      sourceType: 'code',
      objectType: 'step',
      objectName: '步骤条回退确认',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-single-mode-back',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-single-mode-back'),
      display: {
        title: '步骤条回退',
        description: '步骤4中，第1步「上传资料」、第2步「选择识别方式」、第3步「选择识别内容」为可点击回退节点，第4步为当前激活态（绿色高亮）。点击前三步时分别弹出对应确认弹窗。',
        fields: ['步骤条第1步', '步骤条第2步', '步骤条第3步', '步骤条第4步'],
        states: [
          '第1步：可点击，弹出确认更换资料弹窗',
          '第2步：可点击，弹出确认更换识别方式弹窗',
          '第3步：可点击，弹出确认重新选择识别内容弹窗',
          '第4步：绿色高亮当前激活态',
        ],
      },
      operation: {
        title: '回退到前面步骤',
        description: '1、点击「上传资料」→ 弹窗「确认更换资料吗？」「更换资料将清空当前的识别结果。」\n2、点击「选择识别方式」→ 弹窗「确认更换识别方式吗？」「更换识别方式将清空当前的识别结果。」\n3、点击「选择识别内容」→ 弹窗「确认重新选择识别内容吗？」「重新选择识别内容将清空当前识别结果，并恢复进入步骤4之前框选的题目框。」\n4、三个弹窗均为：取消留在步骤4，确认返回对应步骤。',
        permission: '无额外权限限制',
        dataFlow: '确认后按对应回退动作清空识别结果，取消则不清空。回退到步骤3时，回显进入步骤4之前的框选状态，而非进入步骤3时的初始框。',
        exceptions: '未确认前不得离开步骤4。',
      },
      acceptance: [
        '点击步骤1应显示确认更换资料弹窗',
        '点击步骤2应显示确认更换识别方式弹窗',
        '点击步骤3应显示确认重新选择识别内容弹窗',
        '三个弹窗点击取消后均停留在步骤4',
        '三个弹窗点击确认后均返回对应步骤条位置',
      ],
      source: { decisionFile, decisionObject: '步骤条回退确认', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-013',
      title: '题目卡片排序功能移除',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.21',
      objectType: 'button',
      objectName: '题目卡片排序功能',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-question-reorder',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-question-reorder'),
      display: {
        title: '题目卡片排序能力移除',
        description: '本期移除题目卡片拖动排序功能。题目顺序按识别结果和左侧资料题号顺序展示，上移和下移操作保留。【6.21】右侧题卡不按文件名或页码分组展示，不显示文件名/页码分组标题。',
        fields: ['拖动题目顺序功能', '上移题目按钮', '下移题目按钮', '【6.21】新增框插入位置', '【6.21】不显示文件名页码分组'],
        states: [
          '本期移除：不展示拖动排序入口，保留上移下移',
          '题目顺序：按识别结果和左侧资料题号顺序展示',
          '【6.21】新增框插入：以新增框上方已有框对应的右侧题卡为锚点，新题卡显示在该锚点题卡下方',
          '【6.21】右侧列表：不展示文件名/页码分组',
        ],
      },
      operation: {
        title: '题目顺序调整',
        description: '1、本期不支持拖动调整题目顺序。仅支持上移或下移调整题目顺序。\n2、加入试卷时按当前核对列表顺序传递。\n【6.21】3、用户在左侧新增框后，右侧新题卡以新增框上方已有框对应的右侧题卡为锚点插入，显示在该锚点题卡下方，如果右侧题卡曾被上移/下移调整顺序，也按调整后的右侧位置插入。\n【6.21】4、右侧题卡列表不按文件名或页码分组。',
        permission: '无额外权限限制',
        dataFlow: '题目顺序按当前列表顺序传递。【6.21】新增题卡插入位置根据新增框上方已有框与右侧题卡的当前对应关系计算，右侧手动排序结果参与插入位置判断。',
        exceptions: '顺序不符合预期时需返回选择识别内容重新框选或重新识别。【6.21】文件名/页码不作为题卡分组展示依据。',
      },
      acceptance: [
        '题目卡片不展示拖动排序入口',
        '题目卡片保留上移和下移按钮',
        '裁剪功能可用时不与题目排序功能冲突',
        '加入试卷按当前核对列表顺序传递题目',
        '【6.21】左侧新增框后，新题卡应显示在新增框上方已有框对应的右侧题卡下方',
        '【6.21】右侧题卡不应展示文件名/页码分组标题',
      ],
      source: { decisionFile, decisionObject: '题目卡片排序操作 / 6.21 需求评审异常场景', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-014',
      title: '删除题目卡片',
      sourceType: 'code',
      objectType: 'button',
      objectName: '题目卡片删除按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-question-delete',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-question-delete'),
      display: {
        title: '题目卡片删除按钮',
        description: '每张题目卡片头部右侧显示删除图标按钮，默认为灰色，悬停时红色强调并显示「删除题目」提示。',
        fields: ['删除题目按钮', '删除题目提示'],
        states: ['默认态：灰色', '悬停态：红色强调'],
      },
      operation: {
        title: '删除题目',
        description: '1、点击删除后题目卡片从列表移除。\n2、被删除题目的全部内容不再加入试卷。',
        permission: '无额外权限限制',
        dataFlow: '删除后题目不再传递给试卷编辑页面。',
        exceptions: '不提供二次确认和撤销入口，误删后需重新识别或补录。',
      },
      acceptance: [
        '点击删除后题目卡片从列表消失',
        '删除后的题目不加入试卷',
        '删除按钮悬停时有明显红色反馈',
      ],
      source: { decisionFile, decisionObject: '题目卡片删除操作', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-015',
      title: '题目卡片排序（题目+答案模式）',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.21',
      objectType: 'button',
      objectName: '题目+答案模式题目卡片上移/下移按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-question-reorder-stepwise',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-question-reorder-stepwise'),
      display: {
        title: '题目+答案模式下的题目卡片排序',
        description: '题目+答案模式下，题目卡片提供上移、下移操作图标，不提供拖动排序。首题上移置灰，末题下移置灰。【6.21】右侧题卡不按文件名或页码分组展示，不显示文件名/页码分组标题。',
        fields: ['上移题目按钮', '下移题目按钮', '【6.21】新增框插入位置', '【6.21】不显示文件名页码分组'],
        states: [
          '第一张题目：上移置灰',
          '最后一张题目：下移置灰',
          '中间题目：上移和下移均可',
          '【6.21】新增框插入：以新增框上方已有框对应的右侧题卡为锚点，新题卡显示在该锚点题卡下方',
          '【6.21】右侧列表：不展示文件名/页码分组',
        ],
      },
      operation: {
        title: '调整题目顺序',
        description: '1、仅通过上移、下移调整题目顺序，不支持拖拽。\n2、加入试卷时按当前右侧最终顺序传递。\n【6.21】3、用户在左侧新增框后，右侧新题卡以新增框上方已有框对应的右侧题卡为锚点插入，显示在该锚点题卡下方，如果右侧题卡曾被上移/下移调整顺序，也按调整后的右侧位置插入。\n【6.21】4、右侧题卡列表不按文件名或页码分组。',
        permission: '无额外权限限制',
        dataFlow: '排序结果保存在当前列表中，加入试卷时按最终顺序传递。【6.21】新增题卡插入位置根据新增框上方已有框与右侧题卡的当前对应关系计算，右侧手动排序结果参与插入位置判断。',
        exceptions: '边界题目不可继续向对应方向移动。【6.21】文件名/页码不作为题卡分组展示依据。',
      },
      acceptance: [
        '题目卡片展示上移和下移操作图标',
        '题目卡片不展示拖动排序入口',
        '用户只能通过上移、下移改变题目顺序',
        '裁剪功能可用时不与题目排序功能冲突',
        '加入试卷按当前右侧最终顺序传递题目、答案和解析',
        '【6.21】左侧新增框后，新题卡应显示在新增框上方已有框对应的右侧题卡下方',
        '【6.21】右侧题卡不应展示文件名/页码分组标题',
      ],
      source: { decisionFile, decisionObject: '题目+答案模式题目卡片排序操作 / 6.21 需求评审异常场景', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-016',
      title: '删除题目卡片（题目+答案模式）',
      sourceType: 'code',
      objectType: 'button',
      objectName: '题目+答案模式题目卡片删除按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-question-delete-stepwise',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-question-delete-stepwise'),
      display: {
        title: '题目+答案模式下的删除按钮',
        description: '每张题目卡片头部右侧显示删除图标按钮，默认为灰色，悬停时红色强调并显示「删除题目」提示。',
        fields: ['删除题目按钮', '删除题目提示'],
        states: ['默认态：灰色', '悬停态：红色强调'],
      },
      operation: {
        title: '删除题目',
        description: '1、点击删除后题目卡片从列表移除。\n2、被删除题目的全部内容不再加入试卷。',
        permission: '无额外权限限制',
        dataFlow: '删除后题目、答案和解析不再传递给试卷编辑页面。',
        exceptions: '不提供二次确认和撤销入口，误删后需重新识别或补录。',
      },
      acceptance: [
        '点击删除后题目卡片从列表消失',
        '删除后的题目不加入试卷',
        '删除按钮悬停时有明显红色反馈',
      ],
      source: { decisionFile, decisionObject: '题目+答案模式题目卡片删除操作', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-017',
      title: '题型切换结构保护',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '6.5',
      objectType: 'dialog',
      objectName: '切换题型确认弹窗',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-question-type-guard',
      anchorStatus: 'planned',
      activate: activateReview('review-step-question-type-guard'),
      display: {
        title: '切换题型确认',
        description: '题目已有子题、扩展选项、多空答案、答案或解析时，切换题型前显示确认弹窗：「确认切换题型吗？」「切换题型将调整题目结构，可能清空子题的答案及解析」。无结构化内容时直接切换。',
        fields: ['题型选择器', '切换题型确认弹窗', '确认按钮', '取消按钮'],
        states: ['无结构化内容：直接切换', '已有结构化内容：弹窗确认', '取消：保持原题型', '确认：按新题型调整结构'],
      },
      operation: {
        title: '切换题型',
        description: '1、选择新题型后，系统判断是否有子题、扩展选项、多空答案、答案或解析。\n2、有以上内容时先弹窗确认，无则直接切换。\n3、取消保持原题型和原内容，确认后切换并按新题型调整结构。',
        permission: '无额外权限限制',
        dataFlow: '切换后的题型和结构化内容随题目数据传递给试卷编辑页面。',
        exceptions: '已有结构化内容时必须先确认，避免误切题型导致子题内容清空。',
      },
      acceptance: [
        '无结构化内容时可直接切换题型',
        '已有子题、扩展选项、多空答案、答案或解析时先显示确认弹窗',
        '取消后题型和内容不变',
        '确认后才按新题型调整结构',
        '确认弹窗文案与决策一致',
      ],
      source: { decisionFile, decisionObject: '切换题型时已有结构化内容的保护规则', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-018',
      title: '答案解析清空操作',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '6.5',
      objectType: 'button',
      objectName: '答案/解析清空按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-answer-clear',
      anchorStatus: 'planned',
      activate: activateReview('review-step-answer-clear'),
      display: {
        title: '答案解析清空按钮',
        description: '题目卡片和子题区域中有答案、解析或空位答案时，显示对应清空入口（答案区「清空」、解析区「清空」、空位清空图标、子题清空图标）。无内容时隐藏。',
        fields: ['清空答案', '清空解析', '空位答案清空图标', '子题答案清空图标', '子题解析清空图标'],
        states: ['有内容：显示清空入口', '无内容：隐藏清空入口'],
      },
      operation: {
        title: '清空答案解析',
        description: '1、点击清空入口后立即清除对应内容，不弹二次确认。\n2、清空后匹配状态按剩余内容重新计算。',
        permission: '无额外权限限制',
        dataFlow: '清空后的内容保存在当前列表中，加入试卷时按清空后内容传递。',
        exceptions: '不提供撤销入口；误清空需重新输入或重新框选。',
      },
      acceptance: [
        '有内容时显示对应清空入口',
        '无内容时隐藏对应清空入口',
        '点击清空后立即清除对应内容',
        '清空时不弹出二次确认',
        '清空后匹配状态按最新内容更新',
      ],
      source: { decisionFile, decisionObject: '清空答案、解析和空位答案的保护规则', relatedFiles },
    },
    {
      id: 'TABLET_REVIEW_QA_IMAGE-001',
      title: '答案匹配横幅',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '9.2',
      objectType: 'region',
      objectName: '题目+答案图片模式答案匹配状态横幅',
      module: tabletReviewQaImageModuleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 题目+答案模式 → 图片模式',
      anchorId: 'tablet-review-qa-image.match-banner',
      anchorStatus: 'implemented',
      activate: activateTabletReviewQaImage('tablet-review-qa-image.match-banner'),
      display: {
        title: '匹配进度',
        description: [
          '题目+答案图片模式下，右侧题卡列表上方展示答案解析匹配状态横幅。',
          '存在待匹配题目时，横幅展示题目总数、已匹配答案数量和待匹配答案数量，并提示用户可在左侧框选答案或解析手动关联。',
          '全部匹配完成后，横幅展示全部答案已匹配完成的完成态提示。',
        ],
        fields: ['题目总数', '已匹配答案数量', '待匹配答案数量', '手动关联提示'],
        states: ['存在待匹配题目', '全部匹配完成', '匹配失败后可人工补充'],
      },
      operation: {
        title: '查看进度',
        description: [
          '匹配状态横幅不提供收起、展开或跳转操作。',
          '用户根据横幅中的待匹配提示，继续通过答案或解析关联入口补充缺失内容。',
        ],
        permission: '进入题目+答案核对页后可查看匹配状态。',
        dataFlow: '匹配统计根据当前题目、答案、解析和子题答案解析的实际内容实时计算，并参与加入试卷前缺口判断。',
        exceptions: '没有题目结果时不展示匹配状态横幅。',
      },
      acceptance: [
        '存在待匹配答案解析时展示统计横幅',
        '全部匹配后展示完成态提示',
        '横幅统计与题卡答案解析缺失情况一致',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: 'PC REVIEW_STEP-001：匹配状态提示（分步模式）', relatedFiles: tabletReviewQaImageRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_QA_IMAGE-002',
      title: '自动匹配状态',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '9.2',
      objectType: 'state',
      objectName: '答案解析自动匹配中状态',
      module: tabletReviewQaImageModuleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 题目+答案模式 → 图片模式',
      anchorId: 'tablet-review-qa-image.answer-matching',
      anchorStatus: 'implemented',
      activate: activateTabletReviewQaImage('tablet-review-qa-image.answer-matching'),
      display: {
        title: '匹配状态',
        description: [
          '题型识别完成后，题目+答案模式自动进入答案解析匹配阶段。',
          '自动匹配中展示正在匹配答案解析的全局提示，并保持题卡列表可见。',
          '自动匹配失败时展示失败提示，用户可继续人工补充答案或解析。',
        ],
        fields: ['正在匹配答案解析提示', '匹配失败提示', '题卡列表'],
        states: ['匹配中', '匹配完成', '匹配失败'],
      },
      operation: {
        title: '匹配流转',
        description: [
          '同图模式使用当前上传资料进行全局答案解析匹配。',
          '题目文件和答案文件分开时，优先使用答案文件进行全局答案解析匹配。',
          '匹配成功后，把匹配到的答案和解析合并到对应题目或子题。',
        ],
        permission: '题目+答案模式下自动触发，用户无需手动开启。',
        dataFlow: '自动匹配结果写入当前题卡答案、解析和子题答案解析，加入试卷时随题目结构传递。',
        exceptions: '自动匹配失败不清空题目结果，页面保留题卡并提示用户手动关联或编辑补充。',
      },
      acceptance: [
        '题型识别完成后自动进入答案解析匹配',
        '匹配中展示全局提示',
        '匹配失败后保留题目并允许人工补充',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: 'PC 全局答案匹配与自动匹配失败处理', relatedFiles: tabletReviewQaImageRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_QA_IMAGE-003',
      title: '题卡匹配标签',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '9.2',
      objectType: 'state',
      objectName: '题卡答案解析匹配状态标签',
      module: tabletReviewQaImageModuleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 题目+答案模式 → 图片模式',
      anchorId: 'tablet-review-qa-image.match-label',
      anchorStatus: 'implemented',
      activate: activateTabletReviewQaImage('tablet-review-qa-image.match-label'),
      display: {
        title: '缺失标签',
        description: [
          '题目+答案图片模式下，每张题卡按当前答案和解析内容展示匹配状态标签。',
          '答案和解析均存在时展示已匹配状态；缺答案、缺解析、答案解析均缺失时分别展示对应缺失状态。',
          '复合题按子题答案解析和父题解析共同判断缺失状态。',
        ],
        fields: ['答案解析已匹配', '未匹配到答案', '未匹配到解析', '未匹配到答案和解析'],
        states: ['已匹配', '缺答案', '缺解析', '答案解析均缺失'],
      },
      operation: {
        title: '状态更新',
        description: [
          '用户编辑答案或解析后，题卡匹配标签按最新内容重新计算。',
          '用户通过手动关联补充答案或解析后，题卡匹配标签同步更新。',
        ],
        permission: '题目+答案模式下随题卡展示。',
        dataFlow: '匹配标签仅反映当前题卡数据完整性，不额外生成独立数据。',
        exceptions: '题目仍在识别中或题型识别失败时，不按缺答案解析规则展示缺失标签。',
      },
      acceptance: [
        '题卡按实际缺失情况展示匹配标签',
        '编辑或手动关联后标签同步更新',
        '复合题缺失状态按子题口径计算',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: 'PC REVIEW_STEP-003：题目卡片展示（识别题目和答案模式）', relatedFiles: tabletReviewQaImageRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_QA_IMAGE-004',
      title: '父题答案',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '9.2',
      objectType: 'field',
      objectName: '父题答案模块',
      module: tabletReviewQaImageModuleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 题目+答案模式 → 图片模式',
      anchorId: 'tablet-review-qa-image.parent-answer',
      anchorStatus: 'implemented',
      activate: activateTabletReviewQaImage('tablet-review-qa-image.parent-answer'),
      display: {
        title: '答案展示',
        description: [
          '题目+答案图片模式下，非复合题在题目图片下方展示父题答案模块。',
          '选择题答案以选项按钮展示；判断题按对错选项展示；填空题按空位编号展示答案；其他题型展示答案输入区域。',
          '答案缺失时答案模块保留可补充位置，并以缺失状态参与题卡匹配标签和顶部统计。',
        ],
        fields: ['【答】', '选项答案按钮', '填空空位答案', '答案输入区域'],
        states: ['已填答案', '答案缺失', '答案识别中', '查看态', '编辑态'],
      },
      operation: {
        title: '答案维护',
        description: [
          '用户进入当前题卡编辑态后，可手动修改父题答案。',
          '单选题再次点击已选答案可取消选择；多选题可多选并按选项顺序保存；判断题只能在对错范围内选择。',
          '填空题答案按空位分别维护，空位答案汇总为当前题目的答案结构。',
        ],
        permission: '进入当前题卡编辑态后才允许修改父题答案。',
        dataFlow: '父题答案随当前题卡保存，加入试卷时作为题目答案传递。',
        exceptions: '答案为空时不阻断核对流程，但加入试卷前按缺答案解析规则提示确认。',
      },
      acceptance: [
        '非复合题展示父题答案模块',
        '不同题型按对应答案形态展示',
        '编辑态可修改父题答案',
        '答案缺失参与匹配统计',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: 'PC 父题答案字段与选择题/填空题答案结构', relatedFiles: tabletReviewQaImageRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_QA_IMAGE-005',
      title: '父题解析',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '9.2',
      objectType: 'field',
      objectName: '父题解析模块',
      module: tabletReviewQaImageModuleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 题目+答案模式 → 图片模式',
      anchorId: 'tablet-review-qa-image.parent-analysis',
      anchorStatus: 'implemented',
      activate: activateTabletReviewQaImage('tablet-review-qa-image.parent-analysis'),
      display: {
        title: '解析展示',
        description: [
          '题目+答案图片模式下，非复合题在题目图片下方展示父题解析模块。',
          '解析为空时仍保留解析补充位置，并以缺失状态参与题卡匹配标签和顶部统计。',
          '解析识别中时展示解析识别中的加载状态。',
        ],
        fields: ['【析】', '解析输入区域', '解析识别中'],
        states: ['已填解析', '解析缺失', '解析识别中', '查看态', '编辑态'],
      },
      operation: {
        title: '解析维护',
        description: [
          '用户进入当前题卡编辑态后，可手动修改父题解析。',
          '解析可通过【析】关联图标从左侧资料重新框选识别补充。',
        ],
        permission: '进入当前题卡编辑态后才允许修改父题解析。',
        dataFlow: '父题解析随当前题卡保存，加入试卷时作为题目解析传递。',
        exceptions: '解析为空时不阻断核对流程，但加入试卷前按缺答案解析规则提示确认。',
      },
      acceptance: [
        '非复合题展示父题解析模块',
        '编辑态可修改父题解析',
        '解析缺失参与匹配统计',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: 'PC 父题解析字段', relatedFiles: tabletReviewQaImageRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_QA_IMAGE-006',
      title: '答案关联',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '9.2',
      objectType: 'button',
      objectName: '【答】手动关联图标',
      module: tabletReviewQaImageModuleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 题目+答案模式 → 图片模式',
      anchorId: 'tablet-review-qa-image.answer-link-icon',
      anchorStatus: 'implemented',
      activate: activateTabletReviewQaImage('tablet-review-qa-image.answer-link-icon'),
      display: {
        title: '关联入口',
        description: [
          '答案模块左上角展示【答】手动关联图标。',
          '答案缺失时图标显示待补充提示状态；进入答案关联状态后图标高亮；识别中图标显示处理中状态。',
        ],
        fields: ['【答】关联图标', '待补充状态', '关联中状态', '识别中状态'],
        states: ['默认态', '待补充', '关联中', '识别中'],
      },
      operation: {
        title: '手动关联',
        description: [
          '用户点击【答】关联图标后，当前题卡进入答案关联状态；再次点击同一图标退出关联状态。',
          '答案关联状态下，用户在左侧资料中框选答案内容并点击「精准识别」，识别结果写入当前父题或子题答案。',
          '跨文件模式下，点击答案关联入口后应优先定位到答案文件位置；无法定位到具体位置时定位到答案文件开始位置。',
        ],
        permission: '进入题卡编辑态后可使用答案关联入口。',
        dataFlow: '手动关联识别结果写入对应答案字段，并参与题卡匹配状态和加入试卷数据。',
        exceptions: '识别结果不符合当前答案填写规则时，不写入原答案并提示用户重新框选或填写。',
      },
      acceptance: [
        '答案模块展示【答】关联图标',
        '点击后进入或退出答案关联状态',
        '精准识别结果写入对应答案字段',
        '跨文件模式优先定位答案文件',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: 'PC REVIEW_STEP-005：答案关联icon', relatedFiles: tabletReviewQaImageRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_QA_IMAGE-007',
      title: '解析关联',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '9.2',
      objectType: 'button',
      objectName: '【析】手动关联图标',
      module: tabletReviewQaImageModuleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 题目+答案模式 → 图片模式',
      anchorId: 'tablet-review-qa-image.analysis-link-icon',
      anchorStatus: 'implemented',
      activate: activateTabletReviewQaImage('tablet-review-qa-image.analysis-link-icon'),
      display: {
        title: '关联入口',
        description: [
          '解析模块左上角展示【析】手动关联图标。',
          '解析缺失时图标显示待补充提示状态；进入解析关联状态后图标高亮；识别中图标显示处理中状态。',
        ],
        fields: ['【析】关联图标', '待补充状态', '关联中状态', '识别中状态'],
        states: ['默认态', '待补充', '关联中', '识别中'],
      },
      operation: {
        title: '手动关联',
        description: [
          '用户点击【析】关联图标后，当前题卡进入解析关联状态；再次点击同一图标退出关联状态。',
          '解析关联状态下，用户在左侧资料中框选解析内容并点击「精准识别」，识别结果写入当前父题或子题解析。',
          '跨文件模式下，点击解析关联入口后应优先定位到答案文件位置；无法定位到具体位置时定位到答案文件开始位置。',
        ],
        permission: '进入题卡编辑态后可使用解析关联入口。',
        dataFlow: '手动关联识别结果写入对应解析字段，并参与题卡匹配状态和加入试卷数据。',
        exceptions: '识别结果不符合当前解析填写规则时，不写入原解析并提示用户重新框选或填写。',
      },
      acceptance: [
        '解析模块展示【析】关联图标',
        '点击后进入或退出解析关联状态',
        '精准识别结果写入对应解析字段',
        '跨文件模式优先定位答案文件',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: 'PC REVIEW_STEP-005：解析关联icon', relatedFiles: tabletReviewQaImageRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_QA_IMAGE-008',
      title: '关联画框',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '9.2',
      objectType: 'region',
      objectName: '左侧答案/解析精准识别框',
      module: tabletReviewQaImageModuleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 题目+答案模式 → 图片模式',
      anchorId: 'tablet-review-qa-image.precision-box',
      anchorStatus: 'implemented',
      activate: activateTabletReviewQaImage('tablet-review-qa-image.precision-box'),
      display: {
        title: '框选状态',
        description: [
          '进入答案或解析关联状态后，左侧资料页隐藏原有题目识别框，只显示用户本次框选的精准识别框。',
          '拖拽画框时显示青绿色半透明框选区域和放大镜；生成框后显示青绿色精准识别框。',
          '生成精准识别框后，页面中间展示「精准识别」按钮。',
        ],
        fields: ['精准识别框', '放大镜', '精准识别按钮', '删除框按钮', '缩放手柄'],
        states: ['画框中', '已生成精准识别框', '精准识别中'],
      },
      operation: {
        title: '画框识别',
        description: [
          '用户按住并拖拽左侧资料生成精准识别框；框选宽度过小或高度过小时不生成识别框。',
          '精准识别框生成后支持拖动调整位置、拖拽右下角调整大小，也支持点击删除图标取消本次框选。',
          '用户点击「精准识别」后，系统识别框内答案或解析内容；识别完成后清空精准识别框并退出关联状态。',
        ],
        permission: '仅在答案或解析关联状态下允许绘制精准识别框。',
        dataFlow: '精准识别框只服务于当前被关联的答案或解析字段，不改变题目题干框和题卡顺序。',
        exceptions: '精准识别失败时保留当前题卡内容，用户可重新框选或手动填写。',
      },
      acceptance: [
        '关联状态下左侧原识别框隐藏',
        '拖拽时展示框选区域和放大镜',
        '精准识别框可移动、缩放和删除',
        '识别完成后退出关联状态',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: 'PC 手动关联答案框与 Pad 画框交互', relatedFiles: tabletReviewQaImageRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_QA_IMAGE-009',
      title: '取图范围',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '9.2',
      objectType: 'data',
      objectName: '同图/分开答案模式关联取图范围',
      module: tabletReviewQaImageModuleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 题目+答案模式 → 图片模式',
      anchorId: 'tablet-review-qa-image.answer-source-pages',
      anchorStatus: 'implemented',
      activate: activateTabletReviewQaImage('tablet-review-qa-image.answer-source-pages'),
      display: {
        title: '资料范围',
        description: [
          '题目+答案同图模式下，答案解析匹配和手动关联使用当前上传资料页。',
          '题目文件和答案文件分开时，答案解析匹配和手动关联优先使用答案文件页。',
        ],
        fields: ['题目+答案同图资料', '答案文件资料', '左侧资料页'],
        states: ['同图模式', '分开答案模式'],
      },
      operation: {
        title: '取图规则',
        description: [
          '同图模式下，用户在左侧当前资料中框选答案或解析。',
          '分开答案模式下，用户关联答案或解析时应优先定位并框选答案文件；没有具体定位位置时定位到答案文件开始位置。',
        ],
        permission: '用户只能在当前题目+答案任务已上传的资料范围内框选。',
        dataFlow: '被框选资料页裁剪后进入答案或解析识别，结果回填到当前目标字段。',
        exceptions: '答案文件不存在或无法定位时，保留当前页面状态并允许用户手动查找资料页补充。',
      },
      acceptance: [
        '同图模式使用当前资料页匹配答案解析',
        '分开答案模式优先使用答案文件页',
        '无法定位具体位置时定位到答案文件开始位置',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: 'PC 同文件/跨文件答案匹配范围', relatedFiles: tabletReviewQaImageRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_QA_IMAGE-010',
      title: '答案回填',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '9.2',
      objectType: 'data',
      objectName: '答案识别结果回填',
      module: tabletReviewQaImageModuleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 题目+答案模式 → 图片模式',
      anchorId: 'tablet-review-qa-image.answer-fill',
      anchorStatus: 'implemented',
      activate: activateTabletReviewQaImage('tablet-review-qa-image.answer-fill'),
      display: {
        title: '回填结果',
        description: [
          '答案识别完成后，页面在目标答案字段展示最新答案内容。',
          '选择题答案按选项字母展示，填空题答案按空位展示，普通题答案按文本展示。',
        ],
        fields: ['父题答案', '子题答案', '选项答案', '空位答案'],
        states: ['回填成功', '答案为空', '格式不符合'],
      },
      operation: {
        title: '写入规则',
        description: [
          '用户从【答】入口发起精准识别后，识别结果写入当前父题或当前子题答案。',
          '如果框选内容同时包含答案和解析，系统按答案解析结构拆分后分别回显到答案和解析区域。',
          '选择题答案按当前题型规范化保存。',
        ],
        permission: '只有当前被关联的答案字段接收回填结果。',
        dataFlow: '回填后的答案更新当前题卡数据，并参与匹配统计和加入试卷数据。',
        exceptions: '识别结果不符合当前答案填写规范时，不写入内容并提示用户重新框选或填写。',
      },
      acceptance: [
        '答案识别结果回填到目标答案字段',
        '同时识别出答案解析时可拆分回显',
        '格式不符合时不覆盖原答案',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: 'PC 答案手动补录与回填', relatedFiles: tabletReviewQaImageRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_QA_IMAGE-011',
      title: '解析回填',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '9.2',
      objectType: 'data',
      objectName: '解析识别结果回填',
      module: tabletReviewQaImageModuleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 题目+答案模式 → 图片模式',
      anchorId: 'tablet-review-qa-image.analysis-fill',
      anchorStatus: 'implemented',
      activate: activateTabletReviewQaImage('tablet-review-qa-image.analysis-fill'),
      display: {
        title: '回填结果',
        description: [
          '解析识别完成后，页面在目标解析字段展示最新解析内容。',
          '父题解析和子题解析按当前题目结构分别展示。',
        ],
        fields: ['父题解析', '子题解析', '解析文本'],
        states: ['回填成功', '解析为空', '格式不符合'],
      },
      operation: {
        title: '写入规则',
        description: [
          '用户从【析】入口发起精准识别后，识别结果写入当前父题或当前子题解析。',
          '如果框选内容同时包含答案和解析，系统按答案解析结构拆分后分别回显到答案和解析区域。',
        ],
        permission: '只有当前被关联的解析字段接收回填结果。',
        dataFlow: '回填后的解析更新当前题卡数据，并参与匹配统计和加入试卷数据。',
        exceptions: '识别结果不符合当前解析填写规范时，不写入内容并提示用户重新框选或填写。',
      },
      acceptance: [
        '解析识别结果回填到目标解析字段',
        '同时识别出答案解析时可拆分回显',
        '格式不符合时不覆盖原解析',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: 'PC 解析手动补录与回填', relatedFiles: tabletReviewQaImageRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_QA_IMAGE-012',
      title: '填写规范',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '9.2',
      objectType: 'state',
      objectName: '答案/解析不符合填写规范提示',
      module: tabletReviewQaImageModuleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 题目+答案模式 → 图片模式',
      anchorId: 'tablet-review-qa-image.answer-format-error',
      anchorStatus: 'implemented',
      activate: activateTabletReviewQaImage('tablet-review-qa-image.answer-format-error'),
      display: {
        title: '错误提示',
        description: '手动关联识别出的内容不符合当前答案或解析填写规范时，页面提示「不符合答案解析填写规范，请重新框选或填写」。',
        fields: ['不符合答案解析填写规范提示'],
        states: ['格式不符合', '保留原内容'],
      },
      operation: {
        title: '保护规则',
        description: [
          '答案或解析关联识别结果不符合当前字段填写规则时，系统不写入识别结果。',
          '用户需要重新框选或手动填写正确答案解析。',
        ],
        permission: '格式校验只作用于当前被关联的答案或解析字段。',
        dataFlow: '校验失败时保留原答案和解析，不向加入试卷数据写入错误识别结果。',
        exceptions: '校验失败不阻断用户继续编辑、重新框选或继续核对其他题目。',
      },
      acceptance: [
        '格式不符合时展示提示',
        '格式不符合时不覆盖原答案解析',
        '用户可重新框选或手动填写',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: 'PC 6.21：不符合答案解析填写规范', relatedFiles: tabletReviewQaImageRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_QA_IMAGE-013',
      title: '空位答案',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '9.2',
      objectType: 'field',
      objectName: '填空题空位答案',
      module: tabletReviewQaImageModuleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 题目+答案模式 → 图片模式',
      anchorId: 'tablet-review-qa-image.blank-answers',
      anchorStatus: 'implemented',
      activate: activateTabletReviewQaImage('tablet-review-qa-image.blank-answers'),
      display: {
        title: '空位展示',
        description: [
          '填空题答案按空位编号展示，每个空位对应一个答案输入位置。',
          '空位答案为空时保留空位输入位置，并参与答案缺失判断。',
        ],
        fields: ['空位编号', '空位答案输入', '答案汇总'],
        states: ['单空位', '多空位', '空位答案缺失'],
      },
      operation: {
        title: '空位维护',
        description: [
          '用户进入编辑态后，可逐个维护填空题空位答案。',
          '从单空增加到多空时，系统尝试把已有答案拆分到各空位；拆分失败时保留原答案并补充空位。',
          '从多空减少到单空时，系统把已有空位答案合并为单行答案。',
        ],
        permission: '进入当前题卡编辑态后才允许修改空位答案。',
        dataFlow: '空位答案和答案汇总随当前题卡保存，加入试卷时保留填空题多空答案结构。',
        exceptions: '空位答案缺失时不阻断核对流程，但加入试卷前按缺答案解析规则提示确认。',
      },
      acceptance: [
        '填空题按空位展示答案',
        '编辑态可维护每个空位答案',
        '加入试卷保留多空答案结构',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: 'PC 填空题空位答案结构', relatedFiles: tabletReviewQaImageRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_QA_IMAGE-014',
      title: '选择答案',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '9.2',
      objectType: 'field',
      objectName: '选择题答案按钮',
      module: tabletReviewQaImageModuleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 题目+答案模式 → 图片模式',
      anchorId: 'tablet-review-qa-image.choice-answer',
      anchorStatus: 'implemented',
      activate: activateTabletReviewQaImage('tablet-review-qa-image.choice-answer'),
      display: {
        title: '选项答案',
        description: [
          '选择题答案以选项按钮展示，选中项使用高亮状态。',
          '单选题和多选题按当前选项数展示可选字母；判断题固定展示对错两个选项。',
        ],
        fields: ['答案选项按钮', '选中状态', '对错选项'],
        states: ['未选择', '已选择', '多选'],
      },
      operation: {
        title: '选择规则',
        description: [
          '单选题点击一个选项后保存该选项为答案，再次点击已选选项可取消。',
          '多选题允许选择多个选项，保存时按选项顺序排列。',
          '判断题只允许在对错两个选项中选择。',
        ],
        permission: '进入当前题卡编辑态后才允许修改选择题答案。',
        dataFlow: '选择题答案按选项字母保存，加入试卷时随题目答案结构传递。',
        exceptions: '未选择答案时保留空答案状态，并参与缺答案解析判断。',
      },
      acceptance: [
        '选择题以按钮形式展示答案',
        '单选题只能保留一个答案',
        '多选题可保留多个答案且按选项顺序保存',
        '判断题固定对错选项',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: 'PC 选择题答案维护', relatedFiles: tabletReviewQaImageRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_QA_IMAGE-015',
      title: '子题答案',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '9.2',
      objectType: 'field',
      objectName: '复合题子题答案模块',
      module: tabletReviewQaImageModuleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 题目+答案模式 → 图片模式',
      anchorId: 'tablet-review-qa-image.sub-answer',
      anchorStatus: 'implemented',
      activate: activateTabletReviewQaImage('tablet-review-qa-image.sub-answer'),
      display: {
        title: '子题答案',
        description: [
          '复合题图片模式下，每个子题展示独立答案区域。',
          '子题答案按子题题型展示选择题答案、填空空位答案或普通文本答案。',
          '子题答案缺失时参与子题缺口统计。',
        ],
        fields: ['子题序号', '子题答案', '子题答案关联图标'],
        states: ['子题答案已填', '子题答案缺失', '子题答案识别中'],
      },
      operation: {
        title: '子题维护',
        description: [
          '用户进入编辑态后，可维护每个子题的答案。',
          '用户可通过子题【答】关联图标框选识别对应子题答案。',
          '答案框只关联父题时，识别后按子题标记自动拆到子题；不能拆分时保留在父题区。',
        ],
        permission: '进入当前题卡编辑态后才允许修改子题答案。',
        dataFlow: '子题答案作为复合题结构的一部分保存，加入试卷时保留完整子题答案。',
        exceptions: '无法按子题标记拆分答案时，不强行分配到子题。',
      },
      acceptance: [
        '复合题展示子题答案区域',
        '子题答案可手动编辑或关联识别',
        '加入试卷保留子题答案',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: 'PC REVIEW_STEP-004：子题答案结构与编辑', relatedFiles: tabletReviewQaImageRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_QA_IMAGE-016',
      title: '子题解析',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '9.2',
      objectType: 'field',
      objectName: '复合题子题解析模块',
      module: tabletReviewQaImageModuleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 题目+答案模式 → 图片模式',
      anchorId: 'tablet-review-qa-image.sub-analysis',
      anchorStatus: 'implemented',
      activate: activateTabletReviewQaImage('tablet-review-qa-image.sub-analysis'),
      display: {
        title: '子题解析',
        description: [
          '复合题图片模式下，非英语完形填空的子题展示独立解析区域。',
          '英语完形填空子题不展示子题解析，父题保留总解析区域。',
          '子题解析缺失时参与子题缺口统计。',
        ],
        fields: ['子题解析', '父题总解析', '子题解析关联图标'],
        states: ['子题解析已填', '子题解析缺失', '英语完形填空隐藏子题解析'],
      },
      operation: {
        title: '解析维护',
        description: [
          '用户进入编辑态后，可维护每个子题的解析。',
          '用户可通过子题【析】关联图标框选识别对应子题解析。',
          '英语完形填空只维护父题总解析，不要求逐子题解析。',
        ],
        permission: '进入当前题卡编辑态后才允许修改子题解析。',
        dataFlow: '子题解析作为复合题结构的一部分保存；英语完形填空使用父题总解析保存。',
        exceptions: '无法按子题标记拆分解析时，不强行分配到子题。',
      },
      acceptance: [
        '非英语完形填空复合题展示子题解析',
        '英语完形填空隐藏子题解析并展示父题总解析',
        '加入试卷保留子题解析或父题总解析',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: 'PC REVIEW_STEP-004：子题解析结构与编辑', relatedFiles: tabletReviewQaImageRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_QA_IMAGE-022',
      title: '图片模式子题',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '9.2',
      objectType: 'region',
      objectName: '题目+答案图片模式复合题子题结构',
      module: tabletReviewQaImageModuleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 题目+答案模式 → 图片模式',
      anchorId: 'tablet-review-qa-image.subquestions',
      anchorStatus: 'implemented',
      activate: activateTabletReviewQaImage('tablet-review-qa-image.subquestions'),
      display: {
        title: '子题结构',
        description: [
          '题目+答案图片模式下，题卡为复合题时在题目截图下方展示子题结构，复合题默认至少保留 1 个子题。',
          '每个子题展示子题序号、子题题型、答案区域和解析区域；仅英语完型填空子题不展示子题解析，父题展示总解析。',
          '普通复合题子题行展示添加子题入口；子题为选择题或判断题时按答案样式展示选项答案，子题为填空题时展示空位答案。',
          '英语阅读理解的子题题型固定显示为「单选」，不展示可切换的子题题型菜单。',
          '英语完型填空只能通过子题数和选项数维护子题结构，子题固定为单选。',
          '仅有 1 个子题时不展示删除子题入口；存在多个子题时，每个子题行展示删除入口。',
        ],
        fields: ['子题序号', '子题题型', '添加子题', '删除子题', '子题答案', '子题解析', '空位答案'],
        states: ['普通复合题', '英语阅读理解', '英语完型填空', '单子题', '多子题'],
      },
      operation: {
        title: '结构维护',
        description: [
          '普通复合题点击子题行添加入口后，先选择「在上方添加子题」或「在下方添加子题」，再选择子题题型，系统按用户选择的位置插入空子题结构。',
          '新增子题按所选题型初始化对应的答案和解析占位区域；选择题或判断题生成选项答案结构，填空题生成空位答案结构，问答题等普通题型生成答案和解析输入区域。',
          '用户切换普通复合题子题题型后，子题按新题型展示对应答案结构；选择题或判断题展示选项答案，填空题展示空位答案，普通题型展示文本答案。',
          '英语阅读理解点击添加子题时直接新增单选子题，不需要再选择子题题型。',
          '英语完型填空只能通过「子题数」调整子题数量，通过「选项数」统一维护子题选项数量；新增子题固定为单选子题。',
          '删除子题时，如果当前子题没有题干、选项、答案、解析、空位答案或选项解析内容，则直接删除；如果已有内容，弹窗提示「确认删除当前子题吗？」。',
          '删除确认弹窗点击「取消」只关闭弹窗并保留子题；点击「确认」后删除当前子题，删除后的子题不再参与答案解析缺口统计和加入试卷数据。',
        ],
        permission: '当前题卡进入编辑态后可维护图片模式下的子题结构。',
        dataFlow: '题目+答案图片模式下维护的子题结构随当前题卡保存；切换识别模式或加入试卷时，保留已调整的子题数量、子题题型、答案和解析内容。',
        exceptions: [
          '删除到仅剩 1 个子题后不再展示删除入口，避免复合题子题结构为空。',
          '切换识别模式和图片模式时不清空已添加或已删除的子题结构。',
        ],
      },
      acceptance: [
        '题目+答案图片模式复合题默认至少展示 1 个子题结构',
        '普通复合题可从子题行选择上方或下方插入子题',
        '新增子题按题型展示答案和解析占位区域',
        '英语阅读理解子题固定为单选',
        '英语完型填空只能通过子题数和选项数维护结构',
        '仅 1 个子题时不显示删除入口',
        '有内容的子题删除前弹出确认删除当前子题吗',
        '确认删除后子题不再参与缺口统计和加入试卷数据',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: '当前原型已实现：题目+答案图片模式复合题子题结构', relatedFiles: tabletReviewQaImageRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_QA_IMAGE-017',
      title: '人工拆分',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '9.2',
      objectType: 'state',
      objectName: '答案解析待人工拆分提示',
      module: tabletReviewQaImageModuleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 题目+答案模式 → 图片模式',
      anchorId: 'tablet-review-qa-image.manual-split',
      anchorStatus: 'implemented',
      activate: activateTabletReviewQaImage('tablet-review-qa-image.manual-split'),
      display: {
        title: '拆分提示',
        description: [
          '复合题答案或解析无法按明确子题标记拆分时，父题区展示「答案解析待人工拆分」提示。',
          '当前无法拆分的答案或解析保留在父题答案/解析区，提示用户核对后拆到对应子题。',
        ],
        fields: ['答案解析待人工拆分', '父题答案区', '父题解析区'],
        states: ['可自动拆分', '待人工拆分', '已手动拆分'],
      },
      operation: {
        title: '拆分规则',
        description: [
          '系统只按明确子题标记拆分答案和解析。',
          '无法拆分时不丢弃原内容，不自动猜测分配到子题。',
          '用户手动拆分到子题后，待人工拆分提示隐藏。',
        ],
        permission: '进入当前题卡编辑态后可人工拆分答案解析。',
        dataFlow: '拆分后的子题答案解析随复合题结构保存；未拆分内容保留在父题区。',
        exceptions: '题干少于两个子题标记或答案解析缺少明确子题标记时，不自动生成拆分结果。',
      },
      acceptance: [
        '无法拆分时展示待人工拆分提示',
        '无法拆分内容保留在父题区',
        '手动拆分后提示隐藏',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: 'PC 决策 3/12：答案解析自动分发和原始追溯', relatedFiles: tabletReviewQaImageRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_QA_IMAGE-018',
      title: '子题缺口',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '9.2',
      objectType: 'data',
      objectName: '子题答案/解析缺失统计口径',
      module: tabletReviewQaImageModuleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 题目+答案模式 → 图片模式',
      anchorId: 'tablet-review-qa-image.sub-missing-count',
      anchorStatus: 'implemented',
      activate: activateTabletReviewQaImage('tablet-review-qa-image.sub-missing-count'),
      display: {
        title: '缺口统计',
        description: [
          '复合题存在子题时，答案解析缺口按子题答案解析完整性统计。',
          '英语完形填空子题只要求子题答案，父题总解析单独参与缺口判断。',
          '顶部横幅和加入试卷确认弹窗使用同一缺口统计口径。',
        ],
        fields: ['待匹配答案数量', '子题答案缺失', '子题解析缺失', '父题总解析缺失'],
        states: ['子题完整', '子题缺答案', '子题缺解析', '父题总解析缺失'],
      },
      operation: {
        title: '统计规则',
        description: [
          '普通复合题任一子题缺答案或解析时，当前题目计入待补缺口。',
          '英语完形填空任一子题缺答案，或父题总解析缺失时，当前题目计入待补缺口。',
        ],
        permission: '缺口统计随题目+答案模式自动计算。',
        dataFlow: '缺口统计不改变题目内容，只用于横幅展示、题卡标签和加入试卷前确认。',
        exceptions: '题目识别中或题型识别失败时，不参与答案解析缺口统计。',
      },
      acceptance: [
        '子题缺失参与顶部待匹配统计',
        '英语完形填空按子题答案和父题总解析判断',
        '加入试卷确认使用相同统计口径',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: 'PC 决策 5/9：答案匹配状态与待补统计', relatedFiles: tabletReviewQaImageRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_QA_IMAGE-019',
      title: '缺口确认',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '9.2',
      objectType: 'dialog',
      objectName: '缺答案/解析加入确认弹窗',
      module: tabletReviewQaImageModuleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 题目+答案模式 → 图片模式',
      anchorId: 'tablet-review-qa-image.join-missing-dialog',
      anchorStatus: 'implemented',
      activate: activateTabletReviewQaImage('tablet-review-qa-image.join-missing-dialog'),
      display: {
        title: '确认弹窗',
        description: [
          '用户点击加入试卷且仍有答案或解析缺口时，页面展示缺口确认弹窗。',
          '弹窗展示未匹配答案解析的题目数量，并提供取消和继续加入操作。',
        ],
        fields: ['缺口数量', '取消按钮', '继续加入按钮'],
        states: ['存在缺口', '取消', '继续加入'],
      },
      operation: {
        title: '加入保护',
        description: [
          '存在答案或解析缺口时允许带缺口加入，但必须先由用户确认。',
          '用户取消后停留在核对页继续补充。',
          '用户确认后继续执行空题干和编辑中校验，通过后进入加入试卷流程。',
        ],
        permission: '有可加入题目时才能触发加入确认。',
        dataFlow: '确认继续后，当前题目、答案、解析和子题结构按现有内容传递给加入试卷流程。',
        exceptions: '确认缺口加入不自动补全答案解析，后续页面仍按缺失内容处理。',
      },
      acceptance: [
        '有答案解析缺口时点击加入试卷展示确认弹窗',
        '取消后停留核对页',
        '确认后继续后续加入校验',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: 'PC 决策 9/22：加入试卷前缺口确认', relatedFiles: tabletReviewQaImageRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_QA_IMAGE-020',
      title: '加入结构',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '9.2',
      objectType: 'data',
      objectName: '加入试卷数据结构增量',
      module: tabletReviewQaImageModuleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 题目+答案模式 → 图片模式',
      anchorId: 'tablet-review-qa-image.join-data',
      anchorStatus: 'implemented',
      activate: activateTabletReviewQaImage('tablet-review-qa-image.join-data'),
      display: {
        title: '结构范围',
        description: [
          '题目+答案图片模式加入试卷时，相比仅题目模式额外保留答案、解析、子题答案解析和填空空位答案。',
          '题目图片、题型、选项数、子题结构和当前题卡顺序一起保留。',
        ],
        fields: ['答案', '解析', '子题答案', '子题解析', '空位答案', '题目图片'],
        states: ['完整加入', '带缺口加入'],
      },
      operation: {
        title: '数据传递',
        description: [
          '用户确认加入试卷后，当前核对页的题目结构按最终状态传递到试卷编辑页。',
          '带缺口加入时，缺失的答案或解析保持为空，不生成占位答案。',
          '用户编辑、手动关联和自动匹配产生的答案解析均按当前最新值传递。',
        ],
        permission: '加入试卷按钮可用且通过加入前校验后传递数据。',
        dataFlow: '加入试卷数据包含父题、子题、题型、选项数、题目图片、答案、解析、子题答案解析和填空空位答案。',
        exceptions: '题目数据保存失败时阻断加入并提示用户重试。',
      },
      acceptance: [
        '加入试卷保留答案解析增量数据',
        '带缺口加入时缺失字段保持为空',
        '保存失败时停留核对页',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: 'PC 决策 10/27：加入试卷数据结构与失败处理', relatedFiles: tabletReviewQaImageRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_QA_IMAGE-021',
      title: '人工补充',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '9.2',
      objectType: 'state',
      objectName: '自动匹配失败后的人工补充路径',
      module: tabletReviewQaImageModuleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 题目+答案模式 → 图片模式',
      anchorId: 'tablet-review-qa-image.manual-supplement',
      anchorStatus: 'implemented',
      activate: activateTabletReviewQaImage('tablet-review-qa-image.manual-supplement'),
      display: {
        title: '补充入口',
        description: [
          '答案解析自动匹配失败或部分缺失时，题卡仍展示答案和解析模块。',
          '缺失字段通过【答】【析】关联图标、字段编辑区和匹配状态标签提示用户补充。',
        ],
        fields: ['答案模块', '解析模块', '关联图标', '缺失标签'],
        states: ['自动匹配失败', '部分缺失', '人工补充中'],
      },
      operation: {
        title: '补充规则',
        description: [
          '自动匹配失败后不回退到前置步骤，不清空已识别题目。',
          '用户可通过手动关联答案解析、直接编辑字段或继续核对其他题目完成补充。',
          '人工补充后的内容立即参与匹配统计和加入试卷数据。',
        ],
        permission: '进入当前题卡编辑态后可人工补充答案解析。',
        dataFlow: '人工补充结果写入当前题卡，并覆盖对应字段的缺失状态。',
        exceptions: '用户未补齐答案解析时，仍可按缺口确认规则带缺口加入试卷。',
      },
      acceptance: [
        '自动匹配失败后保留题卡',
        '用户可继续手动关联或编辑答案解析',
        '人工补充后匹配统计更新',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: 'PC 自动匹配失败后的人工补充路径', relatedFiles: tabletReviewQaImageRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_IMAGE-001',
      title: '返回保留',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '8.31',
      objectType: 'button',
      objectName: '返回入口',
      module: moduleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 仅题目模式 → 图片模式',
      anchorId: 'tablet-review-image.back',
      anchorStatus: 'implemented',
      activate: activateReview('tablet-review-image.back'),
      display: {
        title: '入口状态',
        description: '核对识别结果页顶部展示返回入口和当前页标题，用户可从该入口回到上一步继续调整识别内容。',
        fields: ['返回入口', '核对识别结果标题'],
        states: ['图片模式下可见'],
      },
      operation: {
        title: '返回规则',
        description: '点击返回后回到「选择识别内容」页，保留已识别题目和框选结果；用户再次进入核对识别结果页时，仍可看到原识别结果。',
        permission: '当前流程内已进入核对页的用户可操作。',
        dataFlow: '返回不清空已识别题目、题卡内容和框选结果。',
        exceptions: '返回后用户如重新选择识别内容，应以后续重新切题和识别结果为准。',
      },
      acceptance: [
        '点击返回后进入选择识别内容页',
        '返回后不清空已识别题目和框选结果',
        '再次进入核对页可继续查看原结果',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: '决策 28：返回入口', relatedFiles: tabletReviewRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_IMAGE-002',
      title: '学科约束',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '8.31',
      objectType: 'field',
      objectName: '学科标签',
      module: moduleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 仅题目模式 → 图片模式',
      anchorId: 'tablet-review-image.subject',
      anchorStatus: 'implemented',
      activate: activateReview('tablet-review-image.subject'),
      display: {
        title: '学科展示',
        description: '页面顶部展示当前识别任务的学段学科，用于提示用户本次题型核对和加入试卷所归属的学科范围。',
        fields: ['学段学科标签'],
        states: ['图片模式下可见'],
      },
      operation: {
        title: '题型范围',
        description: '图片模式下继续按当前学科限制可选题型；用户加入试卷时，题目也按当前学科信息向后续流程传递。',
        permission: '题型可选范围由当前学科决定。',
        dataFlow: '当前学科随题目核对结果一起传递给加入试卷流程。',
        exceptions: '学科信息不应在图片模式和识别模式切换时丢失。',
      },
      acceptance: [
        '顶部展示当前学科',
        '题型选择范围符合当前学科',
        '加入试卷时保留当前学科信息',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: '决策 29：学科标签', relatedFiles: tabletReviewRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_IMAGE-003',
      title: '加入校验',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '8.31',
      objectType: 'button',
      objectName: '加入试卷按钮',
      module: moduleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 仅题目模式 → 图片模式',
      anchorId: 'tablet-review-image.join-paper',
      anchorStatus: 'implemented',
      activate: activateReview('tablet-review-image.join-paper'),
      display: {
        title: '加入试卷按钮',
        description: '顶部步骤条右侧操作区，文案「加入试卷」。有题目时绿色可点击，无题目时置灰。',
        fields: ['加入试卷'],
        states: ['可用态：有题目（绿色可点击）', '禁用态：无题目（灰色）'],
      },
      operation: {
        title: '加入试卷',
        description: '1、点击后检查是否有未匹配答案或解析。\n2、有缺失时弹窗：「确认加入试卷吗？」「当前还有 X 道题的答案/解析没有补充，您可以在后续组卷页面使用AI批量补充功能，进行补充。」（一道大题存在答案或解析未匹配即计1道）。取消停留在步骤4，确认进入后续组卷页面。\n3、确认后完整保留父题、子题、子题答案/解析、填空空位答案、题型、选项数和题目图片传递给下游。\n4、加入试卷前保存当前状态，供从试卷编辑页返回时恢复。\n5、题目数据保存失败时停留在步骤4并提示：「加入试卷失败，题目数据暂未保存，请重试」。',
        permission: '无额外权限限制',
        dataFlow: '题目数据传递给试卷编辑页面，弹窗状态暂存供返回恢复。',
        exceptions: '有未匹配答案/解析时需弹窗二次确认。题目数据保存失败时阻断加入并提示。',
      },
      acceptance: [
        '有题目时按钮可用',
        '无题目时按钮置灰',
        '有答案或解析缺口时显示「确认加入试卷吗？」弹窗',
        '点击取消后停留在步骤4',
        '点击确认后进入后续组卷页面',
        '加入后数据完整传递',
        '题目数据保存失败时停留在核查页并显示失败提示',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: '决策 30：加入试卷', relatedFiles: tabletReviewRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_IMAGE-004',
      title: '框题联动',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '8.31',
      objectType: 'region',
      objectName: '左侧识别框与右侧题卡',
      module: moduleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 仅题目模式 → 图片模式',
      anchorId: 'tablet-review-image.box-card-link',
      anchorStatus: 'implemented',
      activate: activateReview('tablet-review-image.box-card-link'),
      display: {
        title: '联动状态',
        description: '左侧资料展示识别框，右侧展示对应题卡；当前选中的识别框和题卡需要形成清晰的高亮对应关系。',
        fields: ['左侧识别框', '右侧题卡', '选中高亮'],
        states: ['未选中', '已选中'],
      },
      operation: {
        title: '定位规则',
        description: '点击左侧识别框时，右侧定位并高亮对应题卡；点击右侧题卡时，左侧定位并高亮对应识别框。',
        permission: '当前题卡和识别框存在对应关系时可联动。',
        dataFlow: '联动只改变当前选中状态，不改变题目内容和识别结果。',
        exceptions: '如果对应框或题卡已被删除，不再触发对应定位。',
      },
      acceptance: [
        '点击左侧识别框后右侧对应题卡高亮',
        '点击右侧题卡后左侧对应识别框高亮',
        '联动过程不改变题目数据',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: '决策 31：左侧识别框联动', relatedFiles: tabletReviewRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_IMAGE-005',
      title: '补充题框',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '8.31',
      objectType: 'button',
      objectName: '添加识别框按钮',
      module: moduleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 仅题目模式 → 图片模式',
      anchorId: 'tablet-review-image.add-box',
      anchorStatus: 'implemented',
      activate: activateReview('tablet-review-image.add-box'),
      display: {
        title: '入口状态',
        description: '左侧资料工具栏展示「添加识别框」入口，用于在已有识别结果之外补充新的题目框。',
        fields: ['添加识别框按钮', '新增识别框'],
        states: ['未开启添加', '正在添加识别框'],
      },
      operation: {
        title: '补框规则',
        description: '新增识别框后，该框进入待识别状态；用户选中待识别框后，需要点击「继续识别」再生成对应题卡。',
        permission: '用户可在核对页左侧资料上补充题目框。',
        dataFlow: '新增框在继续识别前只作为待识别区域保存，不立即生成题卡。',
        exceptions: '新增框未选中时，不触发继续识别。',
      },
      acceptance: [
        '点击添加识别框后可在左侧资料补充题目框',
        '新增框默认进入待识别状态',
        '新增框需选中并继续识别后才生成题卡',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: '决策 32：添加识别框', relatedFiles: tabletReviewRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_IMAGE-006',
      title: '继续识别',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '8.31',
      objectType: 'button',
      objectName: '继续识别按钮',
      module: moduleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 仅题目模式 → 图片模式',
      anchorId: 'tablet-review-image.continue-recognition',
      anchorStatus: 'implemented',
      activate: activateReview('tablet-review-image.continue-recognition'),
      display: {
        title: '按钮状态',
        description: '当用户选中了待识别框时，页面中部展示「继续识别」按钮；识别处理中按钮不可重复提交。',
        fields: ['继续识别按钮', '待识别框选中状态'],
        states: ['无待识别框选中：隐藏', '有待识别框选中：显示', '识别中：不可重复提交'],
      },
      operation: {
        title: '生成规则',
        description: '点击继续识别后，新增题按左侧资料顺序插入到右侧题卡列表中；如果用户调整的是已有题目的识别框，则覆盖原题卡。',
        permission: '仅选中待识别框后可继续识别。',
        dataFlow: '识别完成后，新增题卡或覆盖后的题卡进入当前核对列表，并参与题数统计和加入试卷。',
        exceptions: '继续识别失败时保留待识别框，用户可重新选择或再次发起识别。',
      },
      acceptance: [
        '选中待识别框后展示继续识别按钮',
        '新增题按左侧资料顺序插入右侧题卡',
        '调整已有题框后继续识别覆盖原题卡',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: '决策 33：继续识别', relatedFiles: tabletReviewRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_IMAGE-007',
      title: '模式切换',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '8.31',
      objectType: 'tab',
      objectName: '识别模式 / 图片模式切换',
      module: moduleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 仅题目模式 → 图片模式',
      anchorId: 'tablet-review-image.mode-switch',
      anchorStatus: 'implemented',
      activate: activateReview('tablet-review-image.mode-switch'),
      display: {
        title: '切换展示',
        description: '右侧题卡区域顶部展示「识别模式 / 图片模式」切换入口，用于切换题卡内容的查看方式。',
        fields: ['识别模式', '图片模式'],
        states: ['识别模式选中', '图片模式选中'],
      },
      operation: {
        title: '保留规则',
        description: '全局切换只改变展示方式，保留题型、题干、裁剪、子题等全部编辑结果。',
        permission: '核对页内用户可在两种查看方式间切换。',
        dataFlow: '切换展示方式不重置题卡数据，也不重新发起识别。',
        exceptions: '切换后仍以用户最后保存的题卡内容作为加入试卷数据。',
      },
      acceptance: [
        '可在识别模式和图片模式之间切换',
        '切换后题型、题干、裁剪和子题结果不丢失',
        '切换不触发重新识别',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: '决策 34：识别模式 / 图片模式', relatedFiles: tabletReviewRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_IMAGE-008',
      title: '题数统计',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '8.31',
      objectType: 'data',
      objectName: '共 X 题',
      module: moduleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 仅题目模式 → 图片模式',
      anchorId: 'tablet-review-image.question-count',
      anchorStatus: 'implemented',
      activate: activateReview('tablet-review-image.question-count'),
      display: {
        title: '统计口径',
        description: '右侧顶部展示「共 X 题」，用于提示当前核对列表中可查看和可处理的题目数量。',
        fields: ['共 X 题'],
        states: ['识别中占位题计入统计', '删除后统计减少'],
      },
      operation: {
        title: '计数规则',
        description: '只统计当前右侧题卡列表中可核对的题目；删除题目后数量减少，识别中的占位题也计入当前数量。',
        permission: '统计面向当前核对流程内所有用户展示。',
        dataFlow: '题数随右侧题卡列表变化实时更新。',
        exceptions: '已删除题目不再计入题数，也不再加入试卷。',
      },
      acceptance: [
        '题数等于当前右侧题卡列表数量',
        '删除题目后题数减少',
        '识别中占位题计入当前题数',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: '决策 35：共 X 题', relatedFiles: tabletReviewRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_IMAGE-009',
      title: '题型',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '8.31',
      objectType: 'field',
      objectName: '题型选择',
      module: moduleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 仅题目模式 → 图片模式',
      anchorId: 'tablet-review-image.question-type',
      anchorStatus: 'implemented',
      activate: activateReview('tablet-review-image.question-type'),
      display: {
        title: '题型展示',
        description: [
          '题卡头部展示题型选择入口，用户进入编辑态后可调整当前题目的题型。',
          '题型识别失败时，题卡头部的题型选择器显示「识别失败」。',
          '失败状态使用橙色边框和橙色文字提示，和正常识别出的绿色题型状态区分。',
        ],
        fields: ['题型选择器', '识别失败文案', '橙色失败状态'],
        states: ['查看态不可编辑', '编辑态可选择', '题型识别失败'],
      },
      operation: {
        title: '切换保护',
        description: [
          '题型可选范围按当前学科限制；已有子题、选项、多空答案等结构化内容时，切换题型前需要弹出确认，避免误清空已有结构。',
          '题型识别请求失败时，题卡保留在核对列表中，并将题型状态标记为识别失败。',
          '用户可通过调整识别框并继续识别，重新获取题型结果。',
          '题型识别失败状态不自动改写为某个默认题型，避免把失败结果误当成已确认题型。',
        ],
        permission: '进入题卡编辑态后才允许修改题型。',
        dataFlow: '确认切换后，题型和对应结构随当前题卡保存，并参与加入试卷。',
        exceptions: [
          '取消切换时保留原题型和原结构；确认切换后按新题型调整结构。',
          '如果所有题目都处于识别失败且没有可加入题目，加入试卷按钮保持不可用。',
        ],
      },
      acceptance: [
        '查看态不能直接修改题型',
        '编辑态可按学科范围选择题型',
        '已有结构化内容时切换题型前弹确认',
        '题型识别失败时题型位置显示识别失败',
        '失败状态使用橙色样式区分',
        '失败题卡不作为可加入题目',
        '重新框选并继续识别后可更新题型状态',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: '决策 36：题型选择', relatedFiles: tabletReviewRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_IMAGE-010',
      title: '编辑范围',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '8.31',
      objectType: 'button',
      objectName: '编辑 / 完成按钮',
      module: moduleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 仅题目模式 → 图片模式',
      anchorId: 'tablet-review-image.edit-toggle',
      anchorStatus: 'implemented',
      activate: activateReview('tablet-review-image.edit-toggle'),
      display: {
        title: '编辑状态',
        description: '题卡头部展示「编辑 / 完成」按钮，用于切换当前题卡的查看态和编辑态。',
        fields: ['编辑按钮', '完成按钮'],
        states: ['查看态：显示编辑', '编辑态：显示完成'],
      },
      operation: {
        title: '可改范围',
        description: '编辑态允许调整题型、裁剪题目截图、配置子题和题型结构；图片模式下不直接编辑题干文本。',
        permission: '用户需要先进入题卡编辑态，才可调整图片模式下的题卡结构。',
        dataFlow: '点击完成后，当前题卡编辑结果保留在核对列表中。',
        exceptions: '未点击完成前，用户继续切换题卡时应避免丢失当前编辑结果。',
      },
      acceptance: [
        '点击编辑后进入题卡编辑态',
        '编辑态支持题型、裁剪和子题结构配置',
        '图片模式下不直接编辑题干文本',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: '决策 37：编辑 / 完成', relatedFiles: tabletReviewRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_IMAGE-011',
      title: '图片裁剪',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '8.31',
      objectType: 'region',
      objectName: '题目截图与裁剪',
      module: moduleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 仅题目模式 → 图片模式',
      anchorId: 'tablet-review-image.crop',
      anchorStatus: 'implemented',
      activate: activateReview('tablet-review-image.crop'),
      display: {
        title: '截图展示',
        description: '图片模式下题卡主体展示题目截图；进入编辑态后，用户可对题目截图进行裁剪。',
        fields: ['题目截图', '裁剪框', '确认裁剪按钮'],
        states: ['查看截图', '正在裁剪'],
      },
      operation: {
        title: '裁剪结果',
        description: '确认裁剪后只更新题目图片，不重新识别题干文本。',
        permission: '进入题卡编辑态后才可裁剪题目截图。',
        dataFlow: '裁剪后的题目图片随当前题卡保存，并作为加入试卷时的题目图片。',
        exceptions: '取消裁剪时保留裁剪前图片。',
      },
      acceptance: [
        '图片模式下展示题目截图',
        '编辑态可调整裁剪区域',
        '确认裁剪后只更新题目图片，不重新识别题干',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: '决策 38：题目截图与裁剪', relatedFiles: tabletReviewRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_IMAGE-012',
      title: '删除题目',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '8.31',
      objectType: 'button',
      objectName: '删除题目按钮',
      module: moduleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 仅题目模式 → 图片模式',
      anchorId: 'tablet-review-image.delete-question',
      anchorStatus: 'implemented',
      activate: activateReview('tablet-review-image.delete-question'),
      display: {
        title: '删除入口',
        description: '题卡头部展示删除题目入口，用户可删除当前不需要加入试卷的题目。',
        fields: ['删除题目按钮'],
        states: ['题卡存在时可见'],
      },
      operation: {
        title: '删除规则',
        description: '删除题卡后，该题不再加入试卷；左侧对应识别框同步移除。',
        permission: '用户可删除当前核对列表中的题目。',
        dataFlow: '删除后题卡列表、左侧识别框、题数统计和加入试卷数据范围同步更新。',
        exceptions: '删除后不提供撤销入口；误删后需要重新添加识别框并继续识别。',
      },
      acceptance: [
        '点击删除后题卡从右侧列表移除',
        '删除后左侧对应识别框同步移除',
        '删除后的题目不再加入试卷',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: '决策 39：删除题目', relatedFiles: tabletReviewRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_IMAGE-013',
      title: '旋转缩放',
      sourceType: 'decision',
      changeType: 'new',
      changeDate: '9.1',
      objectType: 'region',
      objectName: '旋转和放大缩小工具',
      module: moduleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 仅题目模式 → 图片模式',
      anchorId: 'tablet-review-image.rotate-zoom',
      anchorStatus: 'implemented',
      activate: activateReview('tablet-review-image.rotate-zoom'),
      display: {
        title: '工具展示',
        description: '左侧资料工具栏展示旋转和放大缩小能力，用于辅助用户查看资料图片和识别框位置。',
        fields: ['旋转', '缩小', '放大', '缩放比例'],
        states: ['图片模式下可见'],
      },
      operation: {
        title: '沿用线上',
        description: '旋转和放大缩小的能力，和目前线上已经实现的保持一致即可，不用更改。',
        permission: '核对页内查看资料时可使用。',
        dataFlow: '旋转和缩放只影响资料查看效果，不改变题目识别结果和加入试卷数据。',
        exceptions: '如线上已有边界限制，平板端沿用相同限制。',
      },
      acceptance: [
        '旋转和放大缩小工具在左侧资料工具栏可见',
        '能力口径与线上已实现效果保持一致',
        '旋转和缩放不改变题目识别结果',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: '旋转和放大缩小能力沿用线上', relatedFiles: tabletReviewRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_IMAGE-014',
      title: '已识别框',
      sourceType: 'code',
      changeType: 'new',
      changeDate: '9.1',
      objectType: 'region',
      objectName: '左侧已识别框',
      module: moduleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 仅题目模式 → 图片模式',
      anchorId: 'tablet-review-image.recognized-box',
      anchorStatus: 'implemented',
      activate: activateReview('tablet-review-image.recognized-box'),
      display: {
        title: '框状态',
        description: [
          '左侧资料页在原图上叠加展示已经生成题卡的识别框；未选中时以半透明深色区域标出题目范围。',
          '当前题卡对应的识别框显示绿色边框、浅绿色底色和外层高亮，用于提示左侧框与右侧题卡的对应关系。',
          '每个已识别框左上角展示选择控件，右上角展示删除入口，右下角展示拖拽调整大小的控制点。',
        ],
        fields: ['识别框区域', '选中控件', '删除入口', '调整大小控制点', '高亮状态'],
        states: ['未选中', '当前题卡高亮', '已勾选'],
      },
      operation: {
        title: '框操作',
        description: [
          '点击已识别框时，如果该框已关联右侧题卡，则切换右侧对应题卡的当前选中状态。',
          '拖动识别框主体可调整框的位置，拖动右下角控制点可调整框的大小。',
          '调整已识别框后，该框进入待重新识别状态；用户需要勾选该框并点击「继续识别」后，才会用新框范围覆盖更新对应题卡。',
          '点击删除入口会删除该识别框，并同步移除右侧对应题卡。',
        ],
        permission: '核对页左侧已有识别结果时可操作。',
        dataFlow: '已识别框与右侧题卡通过同一题目标识关联；移动、缩放、勾选和删除会更新当前核对页本地状态。',
        exceptions: [
          '框已被删除后，不再参与右侧题卡定位、题数统计和加入试卷。',
          '只移动或缩放已识别框但未继续识别时，不直接改写右侧题干、题型、答案或解析内容。',
        ],
      },
      acceptance: [
        '左侧资料页可看到已生成题卡的识别框',
        '当前题卡对应识别框有绿色高亮',
        '点击已识别框可联动右侧对应题卡',
        '移动或缩放已识别框后显示待重新识别状态',
        '删除已识别框后右侧对应题卡同步移除',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: '当前原型已实现：左侧已识别框', relatedFiles: tabletReviewRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_IMAGE-015',
      title: '新增识别框',
      sourceType: 'code',
      changeType: 'new',
      changeDate: '9.1',
      objectType: 'region',
      objectName: '左侧新增待识别框',
      module: moduleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 仅题目模式 → 图片模式',
      anchorId: 'tablet-review-image.new-box',
      anchorStatus: 'implemented',
      activate: activateReview('tablet-review-image.new-box'),
      display: {
        title: '待识别状态',
        description: [
          '用户开启「添加识别框」后，可在左侧题目资料上拖拽生成新的识别框。',
          '新增识别框以绿色边框和浅绿色底色展示，右上角显示「待识别」标签，用于区分已生成题卡的识别框。',
          '新增识别框同样展示左上角选择控件、右上角删除入口和右下角调整大小控制点。',
        ],
        fields: ['新增识别框', '待识别标签', '选中控件', '删除入口', '调整大小控制点'],
        states: ['待识别', '已勾选待识别', '识别中'],
      },
      operation: {
        title: '补识别',
        description: [
          '新增识别框生成后只保存在左侧资料页，不立即生成右侧题卡。',
          '用户勾选新增识别框后，页面中部显示「继续识别」按钮；点击后对勾选的待识别框发起识别。',
          '继续识别完成后，新增题卡按左侧资料页的页码和位置顺序插入右侧题卡列表，并参与「共 X 题」统计。',
          '识别前用户可继续移动、缩放或删除新增识别框。',
        ],
        permission: '核对页处于图片模式且左侧为题目资料时可补充识别框。',
        dataFlow: '新增识别框在继续识别前只作为待识别区域保存；识别完成后生成题卡并进入当前核对列表。',
        exceptions: [
          '未勾选新增识别框时不显示继续识别入口，也不发起补识别。',
          '继续识别失败时保留新增识别框和待识别状态，用户可调整后再次发起识别。',
        ],
      },
      acceptance: [
        '开启添加识别框后可在左侧资料生成新增框',
        '新增框显示待识别标签',
        '勾选新增框后显示继续识别按钮',
        '继续识别成功后新增题卡按左侧资料顺序插入右侧列表',
        '继续识别失败时新增框保留',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: '当前原型已实现：左侧新增识别框', relatedFiles: tabletReviewRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_IMAGE-016',
      title: '单题视图切换',
      sourceType: 'code',
      changeType: 'new',
      changeDate: '9.1',
      objectType: 'tab',
      objectName: '单题卡识别 / 图片切换',
      module: moduleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 仅题目模式 → 图片模式',
      anchorId: 'tablet-review-image.card-mode-switch',
      anchorStatus: 'implemented',
      activate: activateReview('tablet-review-image.card-mode-switch'),
      display: {
        title: '单题切换',
        description: [
          '每张题卡头部展示「识别 / 图片」切换入口，用于单独控制当前题卡主体展示识别内容还是题目截图。',
          '当前选中的模式以白底和阴影突出，未选中的模式以灰色文字展示。',
          '单题切换只影响当前题卡；右侧顶部的全局「识别模式 / 图片模式」切换会同步调整所有题卡的初始展示模式。',
        ],
        fields: ['识别按钮', '图片按钮', '当前选中状态'],
        states: ['识别选中', '图片选中'],
      },
      operation: {
        title: '切换规则',
        description: [
          '点击「识别」后，当前题卡主体展示识别后的题干内容和题型结构。',
          '点击「图片」后，当前题卡主体展示该题对应的题目截图。',
          '切换单题展示模式时，保留当前题卡的题型、题干、裁剪图片、子题和已编辑内容，不重新发起识别。',
        ],
        permission: '核对页内当前题卡可操作。',
        dataFlow: '单题视图状态只记录在当前题卡上，不改变题目数据和加入试卷内容。',
        exceptions: '识别中题卡先展示识别中占位，识别完成后再按当前题卡视图模式展示。',
      },
      acceptance: [
        '单题卡头部展示识别/图片切换',
        '点击识别只切换当前题卡到识别内容',
        '点击图片只切换当前题卡到题目截图',
        '单题切换不影响其他题卡',
        '切换不清空题型、题干、裁剪、子题和编辑内容',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: '当前原型已实现：单题卡识别 / 图片切换', relatedFiles: tabletReviewRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_IMAGE-017',
      title: '图片模式子题',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '9.2',
      objectType: 'region',
      objectName: '图片模式复合题子题配置区',
      module: moduleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 仅题目模式 → 图片模式',
      anchorId: 'tablet-review-image.subquestions',
      anchorStatus: 'implemented',
      activate: activateReview('tablet-review-image.subquestions'),
      display: {
        title: '子题结构',
        description: [
          '题卡处于图片模式且题型为复合题时，题目截图下方展示子题配置区；复合题默认至少保留 1 个子题结构。',
          '普通复合题子题行展示子题序号、子题题型和行内添加子题入口；子题为选择题或判断题时展示选项数设置，子题为填空题时展示空数设置。',
          '英语阅读理解的子题题型固定显示为「单选」，不展示可切换的子题题型菜单。',
          '英语完型填空不展示逐行添加子题入口，展示「子题数」「题型：单选」「选项数」三个结构维护入口。',
          '仅有 1 个子题时不展示删除子题入口；存在多个子题时，每个子题行展示删除入口。',
        ],
        fields: ['子题序号', '子题题型', '选项数', '空数', '子题数', '添加子题', '删除子题'],
        states: ['普通复合题', '英语阅读理解', '英语完型填空', '单子题', '多子题'],
      },
      operation: {
        title: '结构维护',
        description: [
          '普通复合题点击子题行的添加入口后，先选择「在上方添加子题」或「在下方添加子题」，再选择子题题型，系统按用户选择的位置插入空子题结构。',
          '新增子题按所选题型初始化结构：选择题和判断题生成选项数设置，填空题生成空数设置，问答题等普通子题只生成子题题型结构。',
          '用户切换普通复合题子题题型后，子题按新题型展示对应结构；选择题或判断题显示选项数，填空题显示空数，普通题型不显示结构数量设置。',
          '英语阅读理解点击添加子题时直接新增单选子题，不需要再选择子题题型。',
          '英语完型填空只能通过「子题数」调整子题数量，通过「选项数」统一维护子题选项数量；新增子题固定为单选子题。',
          '仅题目图片模式下删除子题时直接删除，不弹出二次确认；删除后的子题不再参与当前题卡结构和加入试卷数据。',
        ],
        permission: '当前题卡进入编辑态后可维护图片模式下的子题结构。',
        dataFlow: '图片模式下维护的子题结构随当前题卡保存；切换识别模式或加入试卷时，保留已调整的子题数量、子题题型、选项数和空数。',
        exceptions: [
          '删除到仅剩 1 个子题后不再展示删除入口，避免复合题子题结构为空。',
          '切换识别模式和图片模式时不清空已添加或已删除的子题结构。',
        ],
      },
      acceptance: [
        '图片模式复合题默认至少展示 1 个子题结构',
        '普通复合题可从子题行选择上方或下方插入子题',
        '新增子题按题型显示选项数或空数设置',
        '英语阅读理解子题固定为单选',
        '英语完型填空只能通过子题数和选项数维护结构',
        '仅 1 个子题时不显示删除入口',
        '多子题时可直接删除子题且不弹二次确认',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: '当前原型已实现：仅题目图片模式复合题子题结构', relatedFiles: tabletReviewRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_IMAGE-018',
      title: '更多操作',
      sourceType: 'code',
      changeType: 'new',
      changeDate: '9.1',
      objectType: 'button',
      objectName: '三点更多菜单',
      module: moduleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 仅题目模式 → 图片模式',
      anchorId: 'tablet-review-image.more-menu',
      anchorStatus: 'implemented',
      activate: activateReview('tablet-review-image.more-menu'),
      display: {
        title: '菜单展示',
        description: [
          '题卡头部展示三点更多操作入口。',
          '点击后在题卡右上方展开菜单，菜单项依次为「上移」「下移」「搜相似题」。',
          '菜单使用白底、边框和投影展示，覆盖在当前题卡上方。',
        ],
        fields: ['三点按钮', '上移', '下移', '搜相似题'],
        states: ['菜单收起', '菜单展开'],
      },
      operation: {
        title: '菜单操作',
        description: [
          '点击三点按钮时展开或收起当前题卡的更多菜单。',
          '点击「上移」时，当前题卡与上一张题卡交换位置；已是第一张题卡时不改变顺序。',
          '点击「下移」时，当前题卡与下一张题卡交换位置；已是最后一张题卡时不改变顺序。',
          '完成上移或下移后，更多菜单自动收起。',
          '「搜相似题」能力和线上已实现的逻辑保持一致即可。',
        ],
        permission: '核对页内题卡存在时可打开更多菜单。',
        dataFlow: '上移和下移只改变右侧题卡列表顺序，不改变题目内容、题型、左侧识别框范围和加入试卷数据内容。',
        exceptions: '点击「搜相似题」后按线上能力处理；当前原型仅收起菜单，不改变题卡数据。',
      },
      acceptance: [
        '点击三点按钮可展开或收起菜单',
        '菜单展示上移、下移、搜相似题',
        '上移后当前题卡与上一题交换位置',
        '下移后当前题卡与下一题交换位置',
        '第一题上移或最后一题下移不改变顺序',
        '搜相似题按线上能力保持一致',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: '当前原型已实现：三点更多菜单', relatedFiles: tabletReviewRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_RECOGNITION-002',
      title: '题干字段',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '9.1',
      objectType: 'field',
      objectName: '识别模式题干字段',
      module: tabletReviewRecognitionModuleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 仅题目模式 → 识别模式',
      anchorId: 'tablet-review-recognition.stem',
      anchorStatus: 'implemented',
      activate: activateTabletReviewRecognition('tablet-review-recognition.stem'),
      display: {
        title: '题干展示',
        description: [
          '识别模式题干字段展示题目文字内容；换行、选项和子题标记按识别内容保留为可核对文本。',
          '题干为空或未识别出文本时，题干区域仍保留在题卡中，并显示空输入占位「题干」。',
          '题干字段左上角展示【题】手动关联图标，用于把左侧资料中的题干区域重新关联到当前题卡。',
          '进入题干关联状态后，左侧资料页隐藏原有识别框，只显示用户本次框选的精准识别框。',
          '用户拖动画框时，左侧资料页展示青绿色半透明框选区域和放大镜，帮助确认框选边界。',
          '生成精准识别框后，页面中间展示「精准识别」按钮；识别中按钮禁用，关联图标显示处理中状态。',
          '查看态下题干不可直接编辑；编辑态下用户可修改题干文本。',
        ],
        fields: ['题干文本', '题干占位', '【题】关联图标', '左侧精准识别框', '精准识别按钮'],
        states: ['有题干', '题干为空', '只读核对', '编辑中', '题干关联中', '画框中', '精准识别中'],
      },
      operation: {
        title: '题干维护',
        description: [
          '用户点击题卡「编辑」后，可在题干字段中补充或修改题目文字。',
          '用户点击【题】手动关联图标后，当前题卡进入题干关联状态；再次点击同一图标退出关联状态。',
          '题干关联状态下，用户只能在左侧非答案页资料中按住并拖拽生成精准识别框；框选宽度过小或高度过小时不生成识别框。',
          '精准识别框生成后支持拖动调整位置、拖拽右下角调整大小，也支持点击删除图标取消本次框选。',
          '用户点击「精准识别」后，系统识别精准识别框内的内容；识别完成后清空精准识别框并退出题干关联状态。',
          '识别结果为普通文本时，文本回填到当前题卡或当前子题的题干区域。',
          '识别结果包含选项时，系统按选项结果更新当前题卡或当前子题的选项内容，不把选项文本硬塞进题干。',
          '题干关联识别只作为题干内容补充，不改写答案、解析和题型结构。',
          '题干为空的题卡允许停留在核对列表中，用户可在核对页继续补充。',
          '仅题目模式加入试卷前只校验是否存在可加入题目和题干内容，不校验答案或解析。',
        ],
        permission: '进入当前题卡编辑态后才允许修改题干。',
        dataFlow: '用户修改后的题干作为当前题卡内容保存，并作为加入试卷时传递的题目内容。',
        exceptions: '加入试卷时若仍存在题干为空的题目，页面应拦截加入并提示用户补充题干。',
      },
      acceptance: [
        '识别模式展示题干文字',
        '题干为空时题干区域仍保留并显示「题干」占位',
        '查看态不能编辑题干',
        '编辑态可补充题干',
        '点击【题】图标可进入或退出题干手动关联状态',
        '题干关联状态下左侧原有识别框隐藏并可拖拽画出精准识别框',
        '精准识别框可移动、缩放和删除',
        '题干手动关联识别结果回填到当前题卡题干',
        '精准识别完成后退出题干关联状态',
        '空题干加入试卷前被拦截',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: '决策 41：识别模式题干为空或未识别出文本时的展示规则', relatedFiles: tabletReviewRecognitionRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_RECOGNITION-003',
      title: '选择题选项',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '9.1',
      objectType: 'field',
      objectName: '选择题选项区',
      module: tabletReviewRecognitionModuleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 仅题目模式 → 识别模式',
      anchorId: 'tablet-review-recognition.options',
      anchorStatus: 'implemented',
      activate: activateTabletReviewRecognition('tablet-review-recognition.options'),
      display: {
        title: '选项展示',
        description: [
          '题型为单选题、多选题或判断题时，识别模式在题干下方展示选项区。',
          '单选题和多选题按识别文本中实际拆出的连续选项数展示；未拆出时再按识别结果给出的选项数量展示，仍没有数量时默认展示 4 项。',
          '单选题和多选题的选项数量展示范围为 2 到 26 项。',
          '判断题固定展示 2 个选项，分别对应「对」和「错」。',
          '选项区左上角展示【选项】手动关联图标，用于把左侧资料中的选项区域重新关联到当前题卡。',
          '进入选项关联状态后，左侧资料页隐藏原有识别框，只显示用户本次框选的精准识别框。',
          '用户拖动画框时，左侧资料页展示青绿色半透明框选区域和放大镜；生成精准识别框后，页面中间展示「精准识别」按钮。',
        ],
        fields: ['【选项】关联图标', '选项数', '选项 A', '选项 B', '选项内容', '左侧精准识别框', '精准识别按钮'],
        states: ['选择题', '判断题', '选项内容为空', '选项关联中', '画框中', '精准识别中'],
      },
      operation: {
        title: '选项维护',
        description: [
          '进入编辑态后，用户可修改选项内容。',
          '单选题和多选题进入编辑态后可调整选项数；选项数最少 2 项、最多 26 项。',
          '减少选项数时，超出当前数量范围的选项不再展示和传递；增加选项数时，已有选项内容按字母保留，新增选项为空。',
          '判断题不按普通选择题扩展选项数，始终保留 2 个选项。',
          '用户点击【选项】手动关联图标后，当前题卡进入选项关联状态；再次点击同一图标退出关联状态。',
          '选项关联状态下，用户只能在左侧非答案页资料中按住并拖拽生成精准识别框；框选宽度过小或高度过小时不生成识别框。',
          '精准识别框生成后支持拖动调整位置、拖拽右下角调整大小，也支持点击删除图标取消本次框选。',
          '用户点击「精准识别」后，系统识别精准识别框内的内容；识别完成后清空精准识别框并退出选项关联状态。',
          '识别结果包含选项时，选项内容按识别出的选项字母回填到当前题卡或当前子题。',
          '识别结果为普通文本且没有拆出选项时，文本回填到当前题卡或当前子题的题干区域。',
          '选项关联识别出的选项数量多于当前选项数时，选项数自动扩展到识别出的数量，但不超过 26 项。',
          '题型切换为非选择题后，原选择题选项结构按不兼容结构清空。',
        ],
        permission: '进入当前题卡编辑态后才允许修改选项内容或选项数。',
        dataFlow: '选项内容和选项数随当前题卡保存，并作为题目结构的一部分传递给后续试卷编辑。',
        exceptions: '选项内容为空时仍保留对应选项输入位置，用户可在编辑态补充。',
      },
      acceptance: [
        '选择题展示选项区',
        '选项数量优先按识别文本中连续选项数展示',
        '未识别出选项数时默认展示 4 项',
        '普通选择题选项数限制在 2 到 26 项',
        '判断题固定展示对错两个选项',
        '编辑态可修改选项内容和选项数',
        '点击【选项】图标可进入或退出选项手动关联状态',
        '选项关联状态下左侧原有识别框隐藏并可拖拽画出精准识别框',
        '精准识别框可移动、缩放和删除',
        '选项手动关联识别结果按字母回填选项内容',
        '精准识别完成后退出选项关联状态',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: '决策 42：选择题选项区的选项数量来源', relatedFiles: tabletReviewRecognitionRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_RECOGNITION-004',
      title: '填空题空位',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '9.1',
      objectType: 'field',
      objectName: '填空题题干与空位',
      module: tabletReviewRecognitionModuleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 仅题目模式 → 识别模式',
      anchorId: 'tablet-review-recognition.fill-blank',
      anchorStatus: 'implemented',
      activate: activateTabletReviewRecognition('tablet-review-recognition.fill-blank'),
      display: {
        title: '空位展示',
        description: [
          '题型为填空题时，识别模式按题干文本中的空位展示填空位置。',
          '每个空位在题干中以编号空位样式展示，编号按题干内空位顺序从 1 开始。',
          '题干没有空位时，不因为内部识别结果自动展示额外空位；用户可进入编辑态手动增加空位。',
        ],
        fields: ['填空题题干', '空位编号', '挖空入口'],
        states: ['有空位', '无空位', '编辑中'],
      },
      operation: {
        title: '空位维护',
        description: [
          '用户进入编辑态后，可以按当前原型已实现的方式手动增加空位。',
          '用户手动增加空位后，题干中的空位展示和空位数量同步更新。',
          '切换为非填空题后，填空题空位结构按不兼容结构清空。',
        ],
        permission: '进入当前题卡编辑态后才允许维护填空题空位。',
        dataFlow: '题干空位和空位数量随当前题卡保存，并作为题目结构的一部分传递给后续试卷编辑。',
        exceptions: '题干没有空位但题型为填空题时，页面不自动补位；用户需要在编辑态手动增加空位。',
      },
      acceptance: [
        '填空题按题干文本中的空位展示',
        '空位编号按题干顺序从 1 开始',
        '无空位时不自动展示额外空位',
        '编辑态可手动增加空位',
        '手动增加空位后题干展示和空位数量同步更新',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: '决策 43：填空题题干空位与空数的关系', relatedFiles: tabletReviewRecognitionRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_RECOGNITION-005',
      title: '复合题子题',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '9.1',
      objectType: 'region',
      objectName: '复合题/子题区',
      module: tabletReviewRecognitionModuleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 仅题目模式 → 识别模式',
      anchorId: 'tablet-review-recognition.subquestions',
      anchorStatus: 'implemented',
      activate: activateTabletReviewRecognition('tablet-review-recognition.subquestions'),
      display: {
        title: '子题展示',
        description: [
          '题型为复合题时，识别模式在父题题干下方展示子题区。',
          '每个子题展示子题序号、子题题型、子题题干；仅题目模式下不展示子题答案和解析。',
          '英语阅读理解和完形填空的子题题型固定显示为「单选」，不展示可切换的子题题型下拉。',
          '英语完形填空在子题区只展示「子题数」「题型：单选」「选项数」三个结构维护入口，不展示「+ 子题」按钮和子题题型菜单。',
          '其他可添加子题的题型展示子题题型选择器，选项按当前学科可用题型展示，题型名称去掉末尾「题」字。',
          '子题区展示「+ 子题」按钮；父题已是复合题时旁边提示「请核对子题信息」，添加后才转为大题结构时提示「添加后转为大题结构」。',
          '自动拆分失败时仍展示 1 个空子题，提示用户在编辑态继续补充子题内容。',
        ],
        fields: ['子题序号', '子题题型', '子题题干', '子题数', '选项数', '添加子题', '删除子题'],
        states: ['已拆分子题', '空子题', '编辑中'],
      },
      operation: {
        title: '子题维护',
        description: [
          '进入编辑态后，用户可修改子题题型和子题题干。',
          '英语完形填空只能通过「子题数」调整子题数量，通过「选项数」统一调整所有子题的选项数量；新增子题固定为单选子题。',
          '英语阅读理解点击「+ 子题」后直接新增单选子题；其他题型先打开题型菜单，用户选择题型后在当前位置之后新增空子题。',
          '父题不是可添加子题的复合题时，新增子题会先把父题转为当前学科默认复合题结构，再插入空子题。',
          '新增子题按选择的题型初始化兼容结构：选择题生成默认选项结构，填空题生成默认空位结构，普通题保留题干结构。',
          '用户切换子题题型后，子题按新题型保留兼容字段并清空不兼容结构；选择题展示选项结构，填空题展示空位结构，普通非结构题只保留题干。',
          '支持删除子题；删除后该子题不再作为当前题目结构传递给后续试卷编辑。',
        ],
        permission: '进入当前题卡编辑态后才允许维护子题结构。',
        dataFlow: '子题结构随当前题卡保存，并作为复合题结构的一部分传递给后续试卷编辑。',
        exceptions: '自动拆分失败时不阻断核对流程，页面保留 1 个空子题供用户补充。',
      },
      acceptance: [
        '复合题展示子题区',
        '仅题目模式下子题区不展示答案和解析',
        '自动拆分失败时展示 1 个空子题',
        '「+ 子题」按钮可按当前题型规则新增空子题',
        '英语阅读理解和完形填空子题题型固定显示为「单选」',
        '英语完形填空只能通过子题数和选项数维护子题结构',
        '其他复合题子题题型按当前学科可用题型展示并可切换',
        '编辑态可修改子题题型和题干',
        '编辑态可添加或删除子题',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: '决策 44：复合题/子题区的自动拆分失败兜底', relatedFiles: tabletReviewRecognitionRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_RECOGNITION-006',
      title: '题型切换结构',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '9.1',
      objectType: 'data',
      objectName: '题型切换后的识别内容结构',
      module: tabletReviewRecognitionModuleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 仅题目模式 → 识别模式',
      anchorId: 'tablet-review-recognition.type-structure',
      anchorStatus: 'implemented',
      activate: activateTabletReviewRecognition('tablet-review-recognition.type-structure'),
      display: {
        title: '结构联动',
        description: [
          '题型选择器变更后，识别模式题卡主体按新题型展示对应结构。',
          '切换为选择题时展示选项区；切换为填空题时展示填空题题干与空位；切换为复合题时展示子题区；切换为普通非结构题时只展示题干。',
          '切换后不兼容的旧结构不再展示。',
        ],
        fields: ['题型选择器', '题干', '选项区', '填空空位', '子题区'],
        states: ['选择题结构', '填空题结构', '复合题结构', '普通题结构'],
      },
      operation: {
        title: '切换结果',
        description: [
          '题型切换只保留可兼容字段。',
          '切换为非选择题时，原选择题选项结构清空。',
          '复合题切换为普通题时，原子题结构清空。',
          '切换为填空题时，按题干中的空位维护填空题结构。',
        ],
        permission: '进入当前题卡编辑态后才允许修改题型。',
        dataFlow: '题型和切换后的兼容结构随当前题卡保存，并作为加入试卷的数据结构。',
        exceptions: '不兼容结构清空后不提供单独恢复入口；用户需要重新切回题型并手动补充结构。',
      },
      acceptance: [
        '题型切换后题卡主体按新题型展示',
        '切换为选择题后展示选项区',
        '切换为填空题后展示空位结构',
        '切换为复合题后展示子题区',
        '切换为普通题后不再展示选项和子题结构',
        '不兼容结构按确认规则清空',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: '决策 45：题型切换后识别内容结构如何保留或清空', relatedFiles: tabletReviewRecognitionRelatedFiles },
    },
    {
      id: 'TABLET_REVIEW_QA_RECOGNITION-001',
      title: '识别模式题干',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '9.2',
      objectType: 'field',
      objectName: '题目+答案识别模式题干',
      module: tabletReviewQaRecognitionModuleName,
      pageName,
      route: '/tablet-ai-entry → 核对识别结果 → 题目+答案模式 → 识别模式',
      anchorId: 'tablet-review-qa-recognition.stem',
      anchorStatus: 'implemented',
      activate: activateTabletReviewQaRecognition('tablet-review-qa-recognition.stem'),
      display: {
        title: '题干展示',
        description: [
          '题目+答案识别模式下，题卡主体展示识别出的题干文字内容，而不是题目截图。',
          '题干下方继续展示当前题的答案和解析核对区域；本角标只标注识别模式下题干展示的增量逻辑。',
          '题干为空或未识别出文本时，题干区域仍保留在题卡中，并显示空输入占位「题干」。',
          '查看态下题干不可直接编辑；编辑态下用户可修改题干文本。',
        ],
        fields: ['题干文本', '题干占位', '答案区域', '解析区域'],
        states: ['有题干', '题干为空', '只读核对', '编辑中'],
      },
      operation: {
        title: '题干维护',
        description: [
          '用户点击题卡「编辑」后，可在题干字段中补充或修改题目文字。',
          '切换识别模式和图片模式时，保留当前题干、题型、答案、解析和子题结构，不重新发起识别。',
          '用户通过【题】手动关联补充题干时，识别结果回填到当前题干区域，不覆盖答案和解析内容。',
          '题干为空的题卡允许停留在核对列表中，用户可在核对页继续补充。',
        ],
        permission: '进入当前题卡编辑态后才允许修改题干。',
        dataFlow: '用户修改后的题干作为当前题卡内容保存，并在加入试卷时与答案、解析和子题结构一起传递。',
        exceptions: '加入试卷时若仍存在题干为空的题目，页面应拦截加入并提示用户补充题干。',
      },
      acceptance: [
        '题目+答案识别模式展示题干文字',
        '题干为空时题干区域仍保留并显示「题干」占位',
        '题干下方继续展示答案和解析核对区域',
        '查看态不能编辑题干',
        '编辑态可补充题干',
        '题干手动关联识别结果只回填当前题干',
        '切换识别模式和图片模式后保留当前题目结构',
      ],
      source: { decisionFile: tabletReviewDecisionFile, decisionObject: '当前原型已实现：题目+答案识别模式题干增量逻辑', relatedFiles: tabletReviewRecognitionRelatedFiles },
    },
  ],
  excludedDecisions: [
    {
      objectName: '解答题答案/解析自动分发规则中的不可拆分情况',
      reason: '已纳入 REVIEW_STEP-004 的异常处理中',
      sourceDecision: '决策 3',
    },
  ],
  displayOrder: [
    'REVIEW_STEP-006',
    'REVIEW_STEP-002',
    'REVIEW_STEP-013',
    'REVIEW_STEP-014',
    'REVIEW_STEP-007',
    'REVIEW_STEP-012',
    'REVIEW_STEP-008',
    'REVIEW_STEP-009',
    'REVIEW_STEP-001',
    'REVIEW_STEP-003',
    'REVIEW_STEP-015',
    'REVIEW_STEP-016',
    'REVIEW_STEP-017',
    'REVIEW_STEP-005',
    'REVIEW_STEP-018',
    'REVIEW_STEP-004',
    'TABLET_REVIEW_IMAGE-001',
    'TABLET_REVIEW_IMAGE-002',
    'TABLET_REVIEW_IMAGE-003',
    'TABLET_REVIEW_IMAGE-004',
    'TABLET_REVIEW_IMAGE-005',
    'TABLET_REVIEW_IMAGE-006',
    'TABLET_REVIEW_IMAGE-007',
    'TABLET_REVIEW_IMAGE-008',
    'TABLET_REVIEW_IMAGE-009',
    'TABLET_REVIEW_IMAGE-010',
    'TABLET_REVIEW_IMAGE-011',
    'TABLET_REVIEW_IMAGE-012',
    'TABLET_REVIEW_IMAGE-013',
    'TABLET_REVIEW_IMAGE-014',
    'TABLET_REVIEW_IMAGE-015',
    'TABLET_REVIEW_IMAGE-016',
    'TABLET_REVIEW_IMAGE-017',
    'TABLET_REVIEW_IMAGE-018',
    'TABLET_REVIEW_RECOGNITION-002',
    'TABLET_REVIEW_RECOGNITION-003',
    'TABLET_REVIEW_RECOGNITION-004',
    'TABLET_REVIEW_RECOGNITION-005',
    'TABLET_REVIEW_RECOGNITION-006',
    'TABLET_REVIEW_QA_RECOGNITION-001',
    'TABLET_REVIEW_QA_IMAGE-001',
    'TABLET_REVIEW_QA_IMAGE-004',
    'TABLET_REVIEW_QA_IMAGE-005',
    'TABLET_REVIEW_QA_IMAGE-006',
    'TABLET_REVIEW_QA_IMAGE-007',
    'TABLET_REVIEW_QA_IMAGE-008',
    'TABLET_REVIEW_QA_IMAGE-009',
    'TABLET_REVIEW_QA_IMAGE-010',
    'TABLET_REVIEW_QA_IMAGE-013',
    'TABLET_REVIEW_QA_IMAGE-015',
    'TABLET_REVIEW_QA_IMAGE-016',
    'TABLET_REVIEW_QA_IMAGE-022',
    'TABLET_REVIEW_QA_IMAGE-018',
    'TABLET_REVIEW_QA_IMAGE-002',
  ],
  displayNumberMap: {
    'TABLET_REVIEW_IMAGE-001': 1,
    'TABLET_REVIEW_IMAGE-002': 2,
    'TABLET_REVIEW_IMAGE-003': 3,
    'TABLET_REVIEW_IMAGE-004': 4,
    'TABLET_REVIEW_IMAGE-005': 5,
    'TABLET_REVIEW_IMAGE-006': 6,
    'TABLET_REVIEW_IMAGE-007': 7,
    'TABLET_REVIEW_IMAGE-008': 8,
    'TABLET_REVIEW_IMAGE-009': 9,
    'TABLET_REVIEW_IMAGE-010': 10,
    'TABLET_REVIEW_IMAGE-011': 11,
    'TABLET_REVIEW_IMAGE-012': 12,
    'TABLET_REVIEW_IMAGE-013': 13,
    'TABLET_REVIEW_IMAGE-014': 14,
    'TABLET_REVIEW_IMAGE-015': 15,
    'TABLET_REVIEW_IMAGE-016': 16,
    'TABLET_REVIEW_IMAGE-017': 17,
    'TABLET_REVIEW_IMAGE-018': 18,
    'TABLET_REVIEW_RECOGNITION-002': 1,
    'TABLET_REVIEW_RECOGNITION-003': 2,
    'TABLET_REVIEW_RECOGNITION-004': 3,
    'TABLET_REVIEW_RECOGNITION-005': 4,
    'TABLET_REVIEW_RECOGNITION-006': 5,
    'TABLET_REVIEW_QA_RECOGNITION-001': 1,
    'TABLET_REVIEW_QA_IMAGE-001': 1,
    'TABLET_REVIEW_QA_IMAGE-004': 2,
    'TABLET_REVIEW_QA_IMAGE-005': 3,
    'TABLET_REVIEW_QA_IMAGE-006': 4,
    'TABLET_REVIEW_QA_IMAGE-007': 5,
    'TABLET_REVIEW_QA_IMAGE-008': 6,
    'TABLET_REVIEW_QA_IMAGE-009': 7,
    'TABLET_REVIEW_QA_IMAGE-010': 8,
    'TABLET_REVIEW_QA_IMAGE-013': 9,
    'TABLET_REVIEW_QA_IMAGE-015': 10,
    'TABLET_REVIEW_QA_IMAGE-016': 11,
    'TABLET_REVIEW_QA_IMAGE-022': 12,
    'TABLET_REVIEW_QA_IMAGE-018': 13,
    'TABLET_REVIEW_QA_IMAGE-002': 14,
  },
};
