import type { ActivationStep, RequirementRegistry } from './schema';

const relatedFiles = [
  'src/components/UploadQuestionDialog.tsx',
  'src/components/ImportDocumentDialog.tsx',
  'src/app/homework/page.tsx',
];

const pageName = '上传资料';
const route = '/homework → 识别作业资料 → 步骤 1「上传资料」';
const moduleName = '识别作业资料';
const decisionFile = '产品文档/prd-workflow/decisions/upload-files-step.decision.md';

function activateUploadFilesStep(anchorId: string): ActivationStep[] {
  return [
    { type: 'openDialog', label: '打开识别作业资料弹窗', dialog: 'UploadQuestionDialog' },
    { type: 'setStep', label: '切换到上传资料步骤', step: 'upload_files' },
    { type: 'scrollTo', label: '定位页面对象', anchorId },
    { type: 'highlight', label: '高亮页面对象', anchorId },
  ];
}

export const uploadFilesStepRegistry: RequirementRegistry = {
  registryId: 'upload-files-step',
  pageName,
  route,
  module: moduleName,
  description:
    '记录步骤 1「上传资料」的完整页面逻辑，包括资料管理、空态上传、文件列表、删除、追加、识别范围、24 页校验和下一步。',
  sourceDecisionFile: decisionFile,
  relatedFiles,
  displayOrder: [
    'UPLOAD_FILES_STEP-001',
    'UPLOAD_FILES_STEP-005',
    'UPLOAD_FILES_STEP-016',
    'UPLOAD_FILES_STEP-004',
    'UPLOAD_FILES_STEP-002',
    'UPLOAD_FILES_STEP-014',
    'UPLOAD_FILES_STEP-012',
    'UPLOAD_FILES_STEP-003',
    'UPLOAD_FILES_STEP-006',
    'UPLOAD_FILES_STEP-007',
    'UPLOAD_FILES_STEP-008',
    'UPLOAD_FILES_STEP-011',
  ],
  requirements: [
    {
      id: 'UPLOAD_FILES_STEP-001',
      title: '上传资料步骤条',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '6.2',
      objectType: 'step',
      objectName: '上传资料步骤条',
      module: moduleName,
      pageName,
      route,
      anchorId: 'upload-files-step.step-bar',
      anchorStatus: 'implemented',
      activate: activateUploadFilesStep('upload-files-step.step-bar'),
      display: {
        title: '上传资料步骤条展示',
        description:
          '弹窗顶部展示识别流程步骤条。步骤 1「上传资料」为绿色高亮和脉冲圆点，下方显示「管理本次识别的资料文件」。后续步骤按未到达状态展示。',
        fields: ['1. 上传资料', '管理本次识别的资料文件', '后续步骤'],
        states: ['当前步骤', '未到达步骤'],
      },
      operation: {
        title: '步骤条仅展示进度',
        description:
          '步骤条只展示当前流程进度，不可点击切换。用户需从后续步骤返回时，只能通过「修改资料」入口。已完成步骤同样不可点击返回。',
        permission: '沿用作业管理页中 AI 小乐识别资料入口的使用权限。',
        dataFlow: '步骤条不修改本次任务数据。',
        exceptions: '无异常场景',
      },
      acceptance: [
        '步骤 1 应展示为当前高亮状态。',
        '步骤条只展示进度，不允许点击切换步骤。',
        '从后续步骤返回步骤 1 时，只能使用「修改资料」入口。',
      ],
      source: {
        decisionFile,
        decisionObject: '交互：返回「上传资料」的入口',
        relatedFiles,
      },
    },
    {
      id: 'UPLOAD_FILES_STEP-002',
      title: '已上传资料汇总与文件列表',
      sourceType: 'code',
      changeType: 'new',
      changeDate: '6.2',
      objectType: 'region',
      objectName: '已上传资料列表',
      module: moduleName,
      pageName,
      route,
      anchorId: 'upload-files-step.file-list',
      anchorStatus: 'implemented',
      activate: activateUploadFilesStep('upload-files-step.file-list'),
      display: {
        title: '已上传文件列表',
        description:
          '步骤 1 上传区下方以「已上传文件：」标签 + 右侧文件列表的形式展示已添加的文件。每行显示文件图标、文件名称、文件大小、当前识别页数和删除按钮。无文件时展示虚线缺省占位图「暂无文件」。文件检测中显示蓝色旋转加载图标和「检测中...」。',
        fields: ['已上传文件', '文件名称', '文件大小', '识别X页 / 共Y页', '删除按钮', '暂无文件缺省图'],
        states: ['有文件状态', '无文件缺省状态', '文件检测中状态'],
      },
      operation: {
        title: '文件列表管理',
        description:
          '用户可通过文件行的识别页数入口调整范围，或通过删除入口移除单份文件。',
        permission: '沿用作业管理页中 AI 小乐识别资料入口的使用权限。',
        dataFlow: '列表根据本次已添加的文件、识别范围和页数统计生成。',
        exceptions: '暂未取得文件总页数时，只展示当前已知的识别页数。',
      },
      acceptance: [
        '已有资料时应显示文件数量和当前识别总页数。',
        '每份资料应显示文件名称和文件大小。',
        '取得文件页数后，应显示「识别X页 / 共Y页」。',
        '处理失败的资料应在文件行内给出明确失败提示。',
      ],
      source: {
        decisionFile,
        decisionObject: '页面目标：已有资料状态',
        relatedFiles,
      },
    },
    {
      id: 'UPLOAD_FILES_STEP-003',
      title: '文件删除与删除最后一份资料',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '6.2',
      objectType: 'button',
      objectName: '文件删除按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'upload-files-step.file-delete',
      anchorStatus: 'implemented',
      activate: activateUploadFilesStep('upload-files-step.file-delete'),
      display: {
        title: '文件删除入口',
        description:
          '每份资料右侧展示删除按钮。点击后弹出确认弹窗：说明将移除当前文件且不可撤销，底部展示「取消」和「确认删除」按钮。',
        fields: ['删除按钮', '确认删除该文件？', '取消', '确认删除'],
        states: ['文件列表状态', '删除确认弹窗打开状态'],
      },
      operation: {
        title: '删除资料并重新处理',
        description:
          '1、确认删除后，系统从本次任务中移除对应资料。\n2、删除后系统按最新文件列表重新处理全部资料。\n3、删除最后一份资料后，页面回到无资料状态，保留当前学段学科；用户重新上传后可继续任务。',
        permission: '沿用作业管理页中 AI 小乐识别资料入口的使用权限。',
        dataFlow: '删除后更新本次任务的文件列表、识别范围和页数统计，并触发全部资料重新处理。',
        exceptions: '删除最后一份资料后，「下一步」不可用，直到用户重新上传有效资料。',
      },
      acceptance: [
        '点击删除按钮后应展示删除确认弹窗。',
        '确认删除后，对应资料应从列表移除。',
        '删除任意资料后，应按照最新列表重新处理全部资料。',
        '删除最后一份资料后，应展示无资料状态并禁用「下一步」。',
      ],
      source: {
        decisionFile,
        decisionObject: '状态：删除最后一份资料 / 逻辑：修改资料后的重算范围',
        relatedFiles,
      },
    },
    {
      id: 'UPLOAD_FILES_STEP-004',
      title: '无资料状态与直接上传',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.21',
      objectType: 'region',
      objectName: '无资料状态上传区域',
      module: moduleName,
      pageName,
      route,
      anchorId: 'upload-files-step.empty-upload',
      anchorStatus: 'implemented',
      activate: activateUploadFilesStep('upload-files-step.empty-upload'),
      display: {
        title: '上传资料入口',
        description:
          '步骤 1 上传区顶部右侧显示「上传资料」按钮。无已有资料且无已添加文件时，按钮独立显示；有已有资料或有已添加文件时，按钮位于页数提示条右侧。【6.21】上传资料入口遵循乐课网单文件大小上限，超出上限的文件不进入文件列表。',
        fields: ['上传资料按钮', 'CloudUpload 图标', '【6.21】单文件大小上限提示'],
        states: ['无资料态（按钮独立显示）', '有资料态（按钮位于提示条右侧）', '【6.21】单文件超限：显示「请上传 X M 以内的文件」'],
      },
      operation: {
        title: '点击上传文件',
        description:
          '用户点击「上传资料」按钮后调起系统文件选择器，支持 PNG、JPG、JPEG、DOC、DOCX、PDF 格式，可多选。新增文件复用既有的格式校验、重复文件拦截和页数检测规则。【6.21】单文件大小限制与乐课网上传文件大小限制保持一致，用户选择的单个文件超过限制时，系统拦截该文件并提示「请上传 X M 以内的文件」，其中 X 为乐课网文件大小限制数值。',
        permission: '沿用作业管理页中 AI 小乐识别资料入口的使用权限。',
        dataFlow: '有效文件进入当前上传区文件列表，参与页数统计和 24 页上限校验。',
        exceptions:
          '文件格式不支持、重复文件或页数检测失败时，按已确认的拦截规则处理。【6.21】单文件大小超出乐课网上限时，不加入文件列表，并提示「请上传 X M 以内的文件」。',
      },
      acceptance: [
        '无资料时应展示「上传资料」按钮。',
        '点击按钮可选择文件。',
        '无效资料应按既有规则拦截。',
        '【6.21】单文件超出乐课网上限时，应拦截并展示「请上传 X M 以内的文件」提示。',
      ],
      source: {
        decisionFile,
        decisionObject: '上传资料入口 / 6.21 需求评审异常场景',
        relatedFiles,
      },
    },
    {
      id: 'UPLOAD_FILES_STEP-005',
      title: '资料来源与混合使用',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.8',
      objectType: 'tab',
      objectName: '本地上传 / 我的资源库 Tab',
      module: moduleName,
      pageName,
      route,
      anchorId: 'import-document-dialog.tabs',
      anchorStatus: 'implemented',
      activate: activateUploadFilesStep('import-document-dialog.tabs'),
      display: {
        title: '资料来源 Tab 切换',
        description:
          '步骤 1 上传区顶部展示「本地上传」和「我的资源库」两个 Tab。切换后显示对应的上传操作区。首次上传时两个 Tab 均正常展示；补充资料场景下仅展示「本地上传」Tab。',
        fields: ['本地上传 Tab', '我的资源库 Tab'],
        states: ['本地上传选中态', '我的资源库选中态', '补充资料态（隐藏资源库 Tab）'],
      },
      operation: {
        title: '混合使用本地与资源库资料',
        description:
          '1、用户可在本地上传和我的资源库间切换，同一任务允许混合使用两种来源的资料。\n2、用户可重新选择学段学科，新选择的学科对本次任务全部资料统一生效。',
        permission: '学段学科选项沿用当前教师账号在乐课网任教的学段学科数据。',
        dataFlow: '新资料追加到当前任务文件列表，参与总页数统计和 24 页校验；学段学科作为任务统一学科，用于后续识别和加入试卷。',
        exceptions: '补充资料场景下隐藏「我的资源库」Tab，仅可通过本地上传追加文件。',
      },
      acceptance: [
        '未达到 24 页上限时，可以点击「继续上传」。',
        '继续上传时可以选择本地文件或资源库资料。',
        '同一任务可以混合使用两种资料来源。',
        '追加资料后应按照最新资料列表重新处理全部资料。',
        '继续上传时应展示并回显当前任务学段学科。',
        '新选择的学段学科应对当前任务内全部资料统一生效。',
      ],
      source: {
        decisionFile,
        decisionObject: '按钮：「继续上传」允许选择的资料来源',
        relatedFiles,
      },
    },
    {
      id: 'UPLOAD_FILES_STEP-006',
      title: '24 页上限与超限处理',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '6.2',
      objectType: 'state',
      objectName: '24 页上限状态',
      module: moduleName,
      pageName,
      route,
      anchorId: 'upload-files-step.page-limit',
      anchorStatus: 'implemented',
      activate: activateUploadFilesStep('upload-files-step.page-limit'),
      display: {
        title: '超限警告与按钮禁用',
        description:
          '当前选择页数超过 24 页时，页面展示琥珀色警告和「选择识别范围」入口，「下一步」按钮置灰。已达到 24 页时，「继续上传」按钮同步置灰。',
        fields: ['超限警告', '选择识别范围', '继续上传', '下一步'],
        states: ['24 页以内', '已达到 24 页', '超过 24 页'],
      },
      operation: {
        title: '24 页上限拦截',
        description:
          '1、整个识别任务合计最多支持识别 24 页。\n2、超过 24 页时需删除资料或调整识别范围后才可进入下一步。\n3、已满 24 页时不允许继续上传。',
        permission: '沿用作业管理页中 AI 小乐识别资料入口的使用权限。',
        dataFlow: '页面根据当前任务全部资料的识别范围汇总页数，同步更新警告和按钮状态。',
        exceptions: '已满 24 页时，「继续上传」提示：「当前已达 24 页上限，请删除资料或调整识别范围后再继续上传」。',
      },
      acceptance: [
        '当前选择页数超过 24 页时，应展示超限警告。',
        '当前选择页数超过 24 页时，「下一步」应不可用。',
        '当前任务达到 24 页时，「继续上传」应不可用并提供已确认提示。',
      ],
      source: {
        decisionFile,
        decisionObject: '按钮：达到 24 页上限时继续上传',
        relatedFiles,
      },
    },
    {
      id: 'UPLOAD_FILES_STEP-007',
      title: '多文件识别范围调整',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '6.2',
      objectType: 'dialog',
      objectName: '多文件识别范围弹窗',
      module: moduleName,
      pageName,
      route,
      anchorId: 'upload-files-step.range-dialog',
      anchorStatus: 'implemented',
      activate: activateUploadFilesStep('upload-files-step.range-dialog'),
      display: {
        title: '多文件识别范围弹窗',
        description:
          '弹窗展示本次任务全部资料，每行显示文件名称、起始页、结束页、当前识别页数和文件总页数。从某文件行入口进入时，对应文件行高亮。',
        fields: ['文件名称', '起始页', '结束页', '识别X页 / 共Y页', '取消', '确定'],
        states: ['普通文件行', '当前定位文件高亮状态', '范围草稿状态'],
      },
      operation: {
        title: '统一调整多文件范围',
        description:
          '1、文件行识别页数入口和超限警告中的「选择识别范围」入口，统一打开此弹窗。\n2、可在同一弹窗中调整每份资料的连续页码范围。\n3、从某文件行进入时自动定位并高亮该文件。\n4、确认后系统按最新文件列表和识别范围重新处理全部资料。',
        permission: '沿用作业管理页中 AI 小乐识别资料入口的使用权限。',
        dataFlow: '确认后更新本次任务每份资料的识别范围、总页数，并触发重新处理。',
        exceptions: '识别范围仅支持单个连续页码范围。某份资料不参与识别时需删除该资料。',
      },
      acceptance: [
        '所有识别范围入口应打开同一套多文件范围弹窗。',
        '弹窗应展示全部资料的范围信息。',
        '从文件行进入时，应自动定位并高亮对应文件。',
        '确认调整后，应按照最新文件列表和识别范围重新处理全部资料。',
      ],
      source: {
        decisionFile,
        decisionObject: '弹窗：识别范围调整方式',
        relatedFiles,
      },
    },
    {
      id: 'UPLOAD_FILES_STEP-011',
      title: '下一步按钮',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.8',
      objectType: 'button',
      objectName: '下一步按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'import-document-dialog.footer.confirm',
      anchorStatus: 'implemented',
      activate: activateUploadFilesStep('import-document-dialog.footer.confirm'),
      display: {
        title: '下一步按钮',
        description:
          '上传区底部右侧展示「下一步」按钮。已选择学段学科、已有文件、文件页数检测完成且未超 24 页上限时为绿色可用状态；未满足条件时为禁用状态。',
        fields: ['下一步'],
        states: ['可用状态（绿色）', '未选学科禁用', '无文件禁用', '检测中禁用', '超 24 页禁用'],
      },
      operation: {
        title: '提交文件并进入步骤 2',
        description:
          '点击可用「下一步」后，系统将当前上传区的文件提交到本次识别任务，并进入步骤 2「选择识别方式」。文件页数检测未完成或校验未通过时不允许进入下一步。',
        permission: '沿用作业管理页中 AI 小乐识别资料入口的使用权限。',
        dataFlow: '当前上传区文件、识别范围和统一学段学科随「下一步」提交并传给步骤 2。',
        exceptions: '任一前置校验未通过时按钮置灰不可点击。',
      },
      acceptance: [
        '满足全部前置条件时，「下一步」应可用。',
        '无资料、超限、重新处理期间或存在失败文件时，「下一步」应不可用。',
        '点击可用按钮后，应进入步骤 2。',
      ],
      source: {
        decisionFile,
        decisionObject: '状态：删除最后一份资料 / 状态：资料重新处理期间的页面操作 / 异常：资料处理失败',
        relatedFiles,
      },
    },
    {
      id: 'UPLOAD_FILES_STEP-008',
      title: '学段学科必填选择',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '6.8',
      objectType: 'field',
      objectName: '学段学科',
      module: moduleName,
      pageName,
      route,
      anchorId: 'import-document-dialog.subject',
      anchorStatus: 'implemented',
      activate: activateUploadFilesStep('import-document-dialog.subject'),
      display: {
        title: '学段学科字段',
        description:
          '步骤 1 上传区底部左侧显示「学段学科*」必填字段。未选择时显示「请选择学科」，下拉选项展示当前教师账号在乐课网任教的学段学科数据。',
        fields: ['学段学科*', '请选择学科'],
        states: ['未选择态', '已选择态', '下拉展开态'],
      },
      operation: {
        title: '学段学科适用规则',
        description:
          '用户必须选择学段学科后才能提交。选择的学段学科适用于本次识别任务内所有文件或资源。',
        permission: '沿用作业管理页中 AI 小乐识别资料入口的使用权限。',
        dataFlow: '学段学科随资料提交给后续流程，用于识别和题型约束；加入试卷后应带对应学科信息。',
        exceptions: '未选择学段学科时，「下一步」按钮不可点击。',
      },
      acceptance: [
        '应展示学段学科必填字段。',
        '未选择学科时不允许提交。',
        '选择的学科适用于本次任务内所有文件。',
      ],
      source: {
        decisionFile,
        decisionObject: '学段学科：适用范围',
        relatedFiles,
      },
    },
    {
      id: 'UPLOAD_FILES_STEP-012',
      title: '已有资料页数提示',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '6.8',
      objectType: 'region',
      objectName: '页数提示条',
      module: moduleName,
      pageName,
      route,
      anchorId: 'import-document-dialog.local.existing-page-hint',
      anchorStatus: 'implemented',
      activate: activateUploadFilesStep('import-document-dialog.local.existing-page-hint'),
      display: {
        title: '页数提示条展示',
        description:
          '当前任务已有资料时，上传区上方展示蓝色信息条，提示已有识别页数和还可选择的页数。已添加新文件时展示已有页数 + 新选页数 + 剩余可补页数。合计超 24 页时变为红色警告样式。无已有资料时，添加文件后展示蓝色条「本次选择 X 页，还可选择 Y 页」。',
        fields: ['已选择 X 页', '新选择 X 页', '本次选择 X 页', '还可选择 X 页', '超出上限 X 页'],
        states: ['无已有资料无文件态（不显示）', '仅已有资料态（蓝色）', '已有 + 新文件未超限态（蓝色）', '超限警告态（红色）'],
      },
      operation: {
        title: '页数上限联动',
        description:
          '系统汇总当前任务已有页数和本次新选择页数。合计超 24 页时需删除文件或调整识别范围后才能提交。',
        permission: '沿用作业管理页中 AI 小乐识别资料入口的使用权限。',
        dataFlow: '已有页数和本次新选页数共同参与 24 页上限校验，并用于更新剩余可选页数。',
        exceptions: '超限时「下一步」按钮不可用。',
      },
      acceptance: [
        '有已有资料时应展示页数提示条。',
        '添加新文件后应展示已有 + 新增页数。',
        '超限时提示条应变红。',
      ],
      source: {
        decisionFile: '产品文档/prd-workflow/decisions/upload-files-step.decision.md',
        decisionObject: '已有资料页数提示',
        relatedFiles: [...relatedFiles, 'src/app/homework/page.tsx'],
      },
    },
    {
      id: 'UPLOAD_FILES_STEP-014',
      title: '文件列表展示与识别范围',
      sourceType: 'code',
      changeType: 'new',
      changeDate: '6.8',
      objectType: 'data',
      objectName: '文件列表行',
      module: moduleName,
      pageName,
      route,
      anchorId: 'import-document-dialog.local.file-list',
      anchorStatus: 'implemented',
      activate: activateUploadFilesStep('import-document-dialog.local.file-list'),
      display: {
        title: '文件列表行展示',
        description:
          '每行展示文件图标、文件名称、文件大小和「识别 X 页 / 共 Y 页」入口，让用户同时了解当前识别范围和文件完整页数。右侧展示删除按钮。',
        fields: ['文件图标', '文件名称', '文件大小', '识别 X 页 / 共 Y 页', '删除按钮'],
        states: ['文件页数已取得', '文件页数检测中', '识别范围已调整'],
      },
      operation: {
        title: '查看与调整识别范围',
        description:
          '用户可通过「识别 X 页 / 共 Y 页」入口调整单份文件的识别范围。系统保留每份文件的完整页数，用于后续查看和 24 页上限判断。',
        permission: '沿用作业管理页中 AI 小乐识别资料入口的使用权限。',
        dataFlow: '每份文件的完整页数和识别范围随资料进入当前任务。',
        exceptions: '文件页数检测失败时该文件不进入本次任务；完整页数不受识别范围调整影响。',
      },
      acceptance: [
        '每行应展示文件名称和文件大小。',
        '应展示「识别 X 页 / 共 Y 页」。',
        '调整识别范围不影响文件原始总页数。',
      ],
      source: {
        decisionFile,
        decisionObject: '文件列表展示',
        relatedFiles,
      },
    },
    {
      id: 'UPLOAD_FILES_STEP-016',
      title: '暂无文件缺省占位',
      sourceType: 'code',
      changeType: 'new',
      changeDate: '6.8',
      objectType: 'region',
      objectName: '暂无文件缺省图',
      module: moduleName,
      pageName,
      route,
      anchorId: 'upload-files-step.empty-file-placeholder',
      anchorStatus: 'planned',
      activate: activateUploadFilesStep('upload-files-step.empty-file-placeholder'),
      display: {
        title: '暂无文件缺省图',
        description:
          '无已添加文件时，已上传文件标签右侧展示虚线边框缺省占位区：文档图标（半透明）、"暂无文件"文案。',
        fields: ['文档图标', '暂无文件'],
        states: ['无文件态（显示缺省图）', '有文件态（隐藏缺省图，显示文件列表）'],
      },
      operation: {
        title: '纯展示',
        description: '缺省图为纯展示，不可点击、不可交互。',
        permission: '无额外权限限制',
        dataFlow: '无额外数据流转',
        exceptions: '无异常场景',
      },
      acceptance: ['无文件时应展示缺省占位图', '有文件后应切换为文件列表'],
      source: { decisionFile, decisionObject: '暂无文件缺省占位', relatedFiles },
    },
  ],
  excludedDecisions: [
    {
      objectName: '步骤 2、步骤 3 和步骤 4',
      reason: '不属于本轮「上传资料」范围，由对应页面单独审核和沉淀。',
      sourceDecision: '暂不处理',
    },
    {
      objectName: '关闭识别任务',
      reason: '当前「上传资料」前端已移除关闭按钮，不再作为本页右侧 PRD 注释展示。',
      sourceDecision: '按钮：「关闭」',
    },
    {
      objectName: '加入试卷按钮状态',
      reason: '加入试卷入口归属「核对识别结果」，已由核对识别结果页需求覆盖，不再在「上传资料」重复展示。',
      sourceDecision: '按钮：「加入试卷」状态',
    },
  ],
};
